/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Envelope,
  ErrorResponse,
  GenericObject
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get recent social proof events
 * @summary Get recent social proof events
 */
export const getApiV1SocialProofRecent = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/social-proof/recent`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1SocialProofRecentQueryKey = () => {
    return [
    `/api/v1/social-proof/recent`
    ] as const;
    }

    
export const getGetApiV1SocialProofRecentQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError = ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SocialProofRecentQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SocialProofRecent>>> = ({ signal }) => getApiV1SocialProofRecent(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SocialProofRecentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SocialProofRecent>>>
export type GetApiV1SocialProofRecentQueryError = ErrorResponse | ErrorResponse


export function useGetApiV1SocialProofRecent<TData = Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError = ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SocialProofRecent>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SocialProofRecent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SocialProofRecent<TData = Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SocialProofRecent>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SocialProofRecent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SocialProofRecent<TData = Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get recent social proof events
 */

export function useGetApiV1SocialProofRecent<TData = Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialProofRecent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SocialProofRecentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Track and get share URLs for product
 * @summary Track and get share URLs for product
 */
export const postApiV1SocialProofShareProductId = (
    productId: string,
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/social-proof/share/${productId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SocialProofShareProductIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SocialProofShareProductId>>, TError,{productId: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SocialProofShareProductId>>, TError,{productId: string;data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1SocialProofShareProductId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SocialProofShareProductId>>, {productId: string;data: GenericObject}> = (props) => {
          const {productId,data} = props ?? {};

          return  postApiV1SocialProofShareProductId(productId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SocialProofShareProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SocialProofShareProductId>>>
    export type PostApiV1SocialProofShareProductIdMutationBody = GenericObject
    export type PostApiV1SocialProofShareProductIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Track and get share URLs for product
 */
export const usePostApiV1SocialProofShareProductId = <TError = ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SocialProofShareProductId>>, TError,{productId: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SocialProofShareProductId>>,
        TError,
        {productId: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SocialProofShareProductIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    