/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Envelope,
  ErrorResponse,
  GenericObject
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Clear cart
 * @summary Clear cart
 */
export const deleteApiV1Cart = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/cart`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1CartMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1Cart>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1Cart>>, TError,void, TContext> => {

const mutationKey = ['deleteApiV1Cart'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1Cart>>, void> = () => {
          

          return  deleteApiV1Cart(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1CartMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1Cart>>>
    
    export type DeleteApiV1CartMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Clear cart
 */
export const useDeleteApiV1Cart = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1Cart>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1Cart>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDeleteApiV1CartMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get cart; Authenticated customers get persistent cart keyed by ID, guests use X-Cart-Token
 * @summary Get cart
 */
export const getApiV1Cart = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/cart`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1CartQueryKey = () => {
    return [
    `/api/v1/cart`
    ] as const;
    }

    
export const getGetApiV1CartQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Cart>>, TError = ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Cart>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CartQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Cart>>> = ({ signal }) => getApiV1Cart(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Cart>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CartQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Cart>>>
export type GetApiV1CartQueryError = ErrorResponse | ErrorResponse


export function useGetApiV1Cart<TData = Awaited<ReturnType<typeof getApiV1Cart>>, TError = ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Cart>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Cart>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Cart>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Cart<TData = Awaited<ReturnType<typeof getApiV1Cart>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Cart>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Cart>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Cart>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Cart<TData = Awaited<ReturnType<typeof getApiV1Cart>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Cart>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get cart
 */

export function useGetApiV1Cart<TData = Awaited<ReturnType<typeof getApiV1Cart>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Cart>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CartQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Checkout and create order
 * @summary Checkout and create order
 */
export const postApiV1CartCheckout = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/cart/checkout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1CartCheckoutMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CartCheckout>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CartCheckout>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1CartCheckout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CartCheckout>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CartCheckout(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CartCheckoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CartCheckout>>>
    export type PostApiV1CartCheckoutMutationBody = GenericObject
    export type PostApiV1CartCheckoutMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Checkout and create order
 */
export const usePostApiV1CartCheckout = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CartCheckout>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CartCheckout>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1CartCheckoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Remove item from cart
 * @summary Remove item from cart
 */
export const deleteApiV1CartItems = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/cart/items`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1CartItemsMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CartItems>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CartItems>>, TError,void, TContext> => {

const mutationKey = ['deleteApiV1CartItems'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1CartItems>>, void> = () => {
          

          return  deleteApiV1CartItems(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1CartItemsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1CartItems>>>
    
    export type DeleteApiV1CartItemsMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Remove item from cart
 */
export const useDeleteApiV1CartItems = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CartItems>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1CartItems>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDeleteApiV1CartItemsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Update item quantity
 * @summary Update item quantity
 */
export const patchApiV1CartItems = (
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/cart/items`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1CartItemsMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1CartItems>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1CartItems>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1CartItems'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1CartItems>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  patchApiV1CartItems(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1CartItemsMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1CartItems>>>
    export type PatchApiV1CartItemsMutationBody = GenericObject
    export type PatchApiV1CartItemsMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Update item quantity
 */
export const usePatchApiV1CartItems = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1CartItems>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1CartItems>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1CartItemsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Add item to cart
 * @summary Add item to cart
 */
export const postApiV1CartItems = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/cart/items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1CartItemsMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CartItems>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CartItems>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1CartItems'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CartItems>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CartItems(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CartItemsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CartItems>>>
    export type PostApiV1CartItemsMutationBody = GenericObject
    export type PostApiV1CartItemsMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Add item to cart
 */
export const usePostApiV1CartItems = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CartItems>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CartItems>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1CartItemsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Recover abandoned cart
 * @summary Recover abandoned cart
 */
export const getApiV1CartRecover = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/cart/recover`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1CartRecoverQueryKey = () => {
    return [
    `/api/v1/cart/recover`
    ] as const;
    }

    
export const getGetApiV1CartRecoverQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CartRecover>>, TError = ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CartRecover>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CartRecoverQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CartRecover>>> = ({ signal }) => getApiV1CartRecover(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CartRecover>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CartRecoverQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CartRecover>>>
export type GetApiV1CartRecoverQueryError = ErrorResponse | ErrorResponse


export function useGetApiV1CartRecover<TData = Awaited<ReturnType<typeof getApiV1CartRecover>>, TError = ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CartRecover>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CartRecover>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CartRecover>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CartRecover<TData = Awaited<ReturnType<typeof getApiV1CartRecover>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CartRecover>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CartRecover>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CartRecover>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CartRecover<TData = Awaited<ReturnType<typeof getApiV1CartRecover>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CartRecover>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Recover abandoned cart
 */

export function useGetApiV1CartRecover<TData = Awaited<ReturnType<typeof getApiV1CartRecover>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CartRecover>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CartRecoverQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



