/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Envelope,
  ErrorResponse,
  GenericObject
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List subscriptions; Split between staff (all) and customer (own); Tenant-scoped
 * @summary List subscriptions
 */
export const getApiV1Subscriptions = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/subscriptions`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1SubscriptionsQueryKey = () => {
    return [
    `/api/v1/subscriptions`
    ] as const;
    }

    
export const getGetApiV1SubscriptionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SubscriptionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Subscriptions>>> = ({ signal }) => getApiV1Subscriptions(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SubscriptionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Subscriptions>>>
export type GetApiV1SubscriptionsQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1Subscriptions<TData = Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Subscriptions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Subscriptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Subscriptions<TData = Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Subscriptions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Subscriptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Subscriptions<TData = Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List subscriptions
 */

export function useGetApiV1Subscriptions<TData = Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Subscriptions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SubscriptionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Subscribe to plan; Tenant-scoped
 * @summary Subscribe to plan
 */
export const postApiV1Subscriptions = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/subscriptions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SubscriptionsMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Subscriptions>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Subscriptions>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1Subscriptions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Subscriptions>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Subscriptions(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SubscriptionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Subscriptions>>>
    export type PostApiV1SubscriptionsMutationBody = GenericObject
    export type PostApiV1SubscriptionsMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Subscribe to plan
 */
export const usePostApiV1Subscriptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Subscriptions>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Subscriptions>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SubscriptionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get subscription detail; Split between staff and customer (ownership); Tenant-scoped
 * @summary Get subscription detail
 */
export const getApiV1SubscriptionsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/subscriptions/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1SubscriptionsIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/subscriptions/${id}`
    ] as const;
    }

    
export const getGetApiV1SubscriptionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SubscriptionsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SubscriptionsId>>> = ({ signal }) => getApiV1SubscriptionsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SubscriptionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SubscriptionsId>>>
export type GetApiV1SubscriptionsIdQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1SubscriptionsId<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SubscriptionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SubscriptionsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SubscriptionsId<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SubscriptionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SubscriptionsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SubscriptionsId<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get subscription detail
 */

export function useGetApiV1SubscriptionsId<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SubscriptionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Cancel subscription; Tenant-scoped
 * @summary Cancel subscription
 */
export const postApiV1SubscriptionsIdCancel = (
    id: string,
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/subscriptions/${id}/cancel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SubscriptionsIdCancelMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsIdCancel>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsIdCancel>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1SubscriptionsIdCancel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SubscriptionsIdCancel>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SubscriptionsIdCancel(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SubscriptionsIdCancelMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SubscriptionsIdCancel>>>
    export type PostApiV1SubscriptionsIdCancelMutationBody = GenericObject
    export type PostApiV1SubscriptionsIdCancelMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Cancel subscription
 */
export const usePostApiV1SubscriptionsIdCancel = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsIdCancel>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SubscriptionsIdCancel>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SubscriptionsIdCancelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Pause subscription; Tenant-scoped
 * @summary Pause subscription
 */
export const postApiV1SubscriptionsIdPause = (
    id: string,
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/subscriptions/${id}/pause`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SubscriptionsIdPauseMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsIdPause>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsIdPause>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1SubscriptionsIdPause'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SubscriptionsIdPause>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SubscriptionsIdPause(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SubscriptionsIdPauseMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SubscriptionsIdPause>>>
    export type PostApiV1SubscriptionsIdPauseMutationBody = GenericObject
    export type PostApiV1SubscriptionsIdPauseMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Pause subscription
 */
export const usePostApiV1SubscriptionsIdPause = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsIdPause>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SubscriptionsIdPause>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SubscriptionsIdPauseMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Resume subscription; Tenant-scoped
 * @summary Resume subscription
 */
export const postApiV1SubscriptionsIdResume = (
    id: string,
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/subscriptions/${id}/resume`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SubscriptionsIdResumeMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsIdResume>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsIdResume>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1SubscriptionsIdResume'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SubscriptionsIdResume>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SubscriptionsIdResume(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SubscriptionsIdResumeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SubscriptionsIdResume>>>
    export type PostApiV1SubscriptionsIdResumeMutationBody = GenericObject
    export type PostApiV1SubscriptionsIdResumeMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Resume subscription
 */
export const usePostApiV1SubscriptionsIdResume = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsIdResume>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SubscriptionsIdResume>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SubscriptionsIdResumeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List subscription plans; Split between staff (all) and customer (public); Tenant-scoped
 * @summary List subscription plans
 */
export const getApiV1SubscriptionsPlans = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/subscriptions/plans`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1SubscriptionsPlansQueryKey = () => {
    return [
    `/api/v1/subscriptions/plans`
    ] as const;
    }

    
export const getGetApiV1SubscriptionsPlansQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SubscriptionsPlansQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>> = ({ signal }) => getApiV1SubscriptionsPlans(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SubscriptionsPlansQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>>
export type GetApiV1SubscriptionsPlansQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1SubscriptionsPlans<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SubscriptionsPlans<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SubscriptionsPlans<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List subscription plans
 */

export function useGetApiV1SubscriptionsPlans<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlans>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SubscriptionsPlansQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create subscription plan; Tenant-scoped
 * @summary Create subscription plan
 */
export const postApiV1SubscriptionsPlans = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/subscriptions/plans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SubscriptionsPlansMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsPlans>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsPlans>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1SubscriptionsPlans'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SubscriptionsPlans>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SubscriptionsPlans(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SubscriptionsPlansMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SubscriptionsPlans>>>
    export type PostApiV1SubscriptionsPlansMutationBody = GenericObject
    export type PostApiV1SubscriptionsPlansMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Create subscription plan
 */
export const usePostApiV1SubscriptionsPlans = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SubscriptionsPlans>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SubscriptionsPlans>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SubscriptionsPlansMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete subscription plan; Tenant-scoped
 * @summary Delete subscription plan
 */
export const deleteApiV1SubscriptionsPlansId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/subscriptions/plans/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1SubscriptionsPlansIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SubscriptionsPlansId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SubscriptionsPlansId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1SubscriptionsPlansId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1SubscriptionsPlansId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1SubscriptionsPlansId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1SubscriptionsPlansIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1SubscriptionsPlansId>>>
    
    export type DeleteApiV1SubscriptionsPlansIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Delete subscription plan
 */
export const useDeleteApiV1SubscriptionsPlansId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SubscriptionsPlansId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1SubscriptionsPlansId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1SubscriptionsPlansIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get plan detail; Tenant-scoped
 * @summary Get plan detail
 */
export const getApiV1SubscriptionsPlansId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/subscriptions/plans/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1SubscriptionsPlansIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/subscriptions/plans/${id}`
    ] as const;
    }

    
export const getGetApiV1SubscriptionsPlansIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SubscriptionsPlansIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>> = ({ signal }) => getApiV1SubscriptionsPlansId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SubscriptionsPlansIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>>
export type GetApiV1SubscriptionsPlansIdQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1SubscriptionsPlansId<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SubscriptionsPlansId<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SubscriptionsPlansId<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get plan detail
 */

export function useGetApiV1SubscriptionsPlansId<TData = Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SubscriptionsPlansId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SubscriptionsPlansIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update subscription plan; Tenant-scoped
 * @summary Update subscription plan
 */
export const patchApiV1SubscriptionsPlansId = (
    id: string,
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/subscriptions/plans/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1SubscriptionsPlansIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SubscriptionsPlansId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SubscriptionsPlansId>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1SubscriptionsPlansId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1SubscriptionsPlansId>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1SubscriptionsPlansId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1SubscriptionsPlansIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1SubscriptionsPlansId>>>
    export type PatchApiV1SubscriptionsPlansIdMutationBody = GenericObject
    export type PatchApiV1SubscriptionsPlansIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update subscription plan
 */
export const usePatchApiV1SubscriptionsPlansId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SubscriptionsPlansId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1SubscriptionsPlansId>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1SubscriptionsPlansIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    