// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consent_log.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConsentLog = `-- name: CreateConsentLog :one
INSERT INTO consent_log (customer_id, consent_type, ip_address, user_agent, terms_version)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, consent_type, ip_address, user_agent, terms_version, consented_at
`

type CreateConsentLogParams struct {
	CustomerID   uuid.UUID   `json:"customer_id"`
	ConsentType  string      `json:"consent_type"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	TermsVersion pgtype.Text `json:"terms_version"`
}

func (q *Queries) CreateConsentLog(ctx context.Context, arg CreateConsentLogParams) (ConsentLog, error) {
	row := q.db.QueryRow(ctx, createConsentLog,
		arg.CustomerID,
		arg.ConsentType,
		arg.IpAddress,
		arg.UserAgent,
		arg.TermsVersion,
	)
	var i ConsentLog
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ConsentType,
		&i.IpAddress,
		&i.UserAgent,
		&i.TermsVersion,
		&i.ConsentedAt,
	)
	return i, err
}

const listConsentsByCustomer = `-- name: ListConsentsByCustomer :many
SELECT id, customer_id, consent_type, ip_address, user_agent, terms_version, consented_at FROM consent_log
WHERE customer_id = $1
ORDER BY consented_at DESC
`

func (q *Queries) ListConsentsByCustomer(ctx context.Context, customerID uuid.UUID) ([]ConsentLog, error) {
	rows, err := q.db.Query(ctx, listConsentsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsentLog
	for rows.Next() {
		var i ConsentLog
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ConsentType,
			&i.IpAddress,
			&i.UserAgent,
			&i.TermsVersion,
			&i.ConsentedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
