// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coupons.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoupon = `-- name: CreateCoupon :one

INSERT INTO coupons (
    shop_id, code, type, value, is_active, expires_at, min_order_amount, usage_limit
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, shop_id, code, type, value, is_active, expires_at, min_order_amount, usage_limit, usage_count
`

type CreateCouponParams struct {
	ShopID         pgtype.UUID        `json:"shop_id"`
	Code           string             `json:"code"`
	Type           DiscountType       `json:"type"`
	Value          pgtype.Numeric     `json:"value"`
	IsActive       pgtype.Bool        `json:"is_active"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	MinOrderAmount pgtype.Numeric     `json:"min_order_amount"`
	UsageLimit     pgtype.Int4        `json:"usage_limit"`
}

// ==================== Coupons ====================
func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.ShopID,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.IsActive,
		arg.ExpiresAt,
		arg.MinOrderAmount,
		arg.UsageLimit,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.IsActive,
		&i.ExpiresAt,
		&i.MinOrderAmount,
		&i.UsageLimit,
		&i.UsageCount,
	)
	return i, err
}

const deleteCoupon = `-- name: DeleteCoupon :exec
DELETE FROM coupons WHERE id = $1 AND shop_id = $2
`

type DeleteCouponParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) DeleteCoupon(ctx context.Context, arg DeleteCouponParams) error {
	_, err := q.db.Exec(ctx, deleteCoupon, arg.ID, arg.ShopID)
	return err
}

const getCoupon = `-- name: GetCoupon :one
SELECT id, shop_id, code, type, value, is_active, expires_at, min_order_amount, usage_limit, usage_count FROM coupons
WHERE id = $1 AND shop_id = $2
`

type GetCouponParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) GetCoupon(ctx context.Context, arg GetCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCoupon, arg.ID, arg.ShopID)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.IsActive,
		&i.ExpiresAt,
		&i.MinOrderAmount,
		&i.UsageLimit,
		&i.UsageCount,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, shop_id, code, type, value, is_active, expires_at, min_order_amount, usage_limit, usage_count FROM coupons
WHERE code = $1 AND shop_id = $2
`

type GetCouponByCodeParams struct {
	Code   string      `json:"code"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) GetCouponByCode(ctx context.Context, arg GetCouponByCodeParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, arg.Code, arg.ShopID)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.IsActive,
		&i.ExpiresAt,
		&i.MinOrderAmount,
		&i.UsageLimit,
		&i.UsageCount,
	)
	return i, err
}

const incrementCouponUsage = `-- name: IncrementCouponUsage :one
UPDATE coupons
SET usage_count = usage_count + 1
WHERE id = $1 AND shop_id = $2
RETURNING usage_count
`

type IncrementCouponUsageParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) IncrementCouponUsage(ctx context.Context, arg IncrementCouponUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementCouponUsage, arg.ID, arg.ShopID)
	var usage_count int32
	err := row.Scan(&usage_count)
	return usage_count, err
}

const listActiveCoupons = `-- name: ListActiveCoupons :many
SELECT id, shop_id, code, type, value, is_active, expires_at, min_order_amount, usage_limit, usage_count FROM coupons
WHERE shop_id = $1 AND is_active = TRUE
ORDER BY code ASC
`

func (q *Queries) ListActiveCoupons(ctx context.Context, shopID pgtype.UUID) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listActiveCoupons, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Code,
			&i.Type,
			&i.Value,
			&i.IsActive,
			&i.ExpiresAt,
			&i.MinOrderAmount,
			&i.UsageLimit,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoupons = `-- name: ListCoupons :many
SELECT id, shop_id, code, type, value, is_active, expires_at, min_order_amount, usage_limit, usage_count FROM coupons
WHERE shop_id = $1
ORDER BY code ASC
`

func (q *Queries) ListCoupons(ctx context.Context, shopID pgtype.UUID) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listCoupons, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Code,
			&i.Type,
			&i.Value,
			&i.IsActive,
			&i.ExpiresAt,
			&i.MinOrderAmount,
			&i.UsageLimit,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleCoupon = `-- name: ToggleCoupon :one
UPDATE coupons SET is_active = NOT is_active
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, code, type, value, is_active, expires_at, min_order_amount, usage_limit, usage_count
`

type ToggleCouponParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) ToggleCoupon(ctx context.Context, arg ToggleCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, toggleCoupon, arg.ID, arg.ShopID)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.IsActive,
		&i.ExpiresAt,
		&i.MinOrderAmount,
		&i.UsageLimit,
		&i.UsageCount,
	)
	return i, err
}

const updateCoupon = `-- name: UpdateCoupon :one
UPDATE coupons SET
    code = COALESCE($1, code),
    type = COALESCE($2, type),
    value = COALESCE($3, value),
    is_active = COALESCE($4, is_active),
    expires_at = COALESCE($5, expires_at),
    min_order_amount = COALESCE($6, min_order_amount),
    usage_limit = COALESCE($7, usage_limit)
WHERE id = $8 AND shop_id = $9
RETURNING id, shop_id, code, type, value, is_active, expires_at, min_order_amount, usage_limit, usage_count
`

type UpdateCouponParams struct {
	Code           pgtype.Text        `json:"code"`
	Type           NullDiscountType   `json:"type"`
	Value          pgtype.Numeric     `json:"value"`
	IsActive       pgtype.Bool        `json:"is_active"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	MinOrderAmount pgtype.Numeric     `json:"min_order_amount"`
	UsageLimit     pgtype.Int4        `json:"usage_limit"`
	ID             uuid.UUID          `json:"id"`
	ShopID         pgtype.UUID        `json:"shop_id"`
}

func (q *Queries) UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, updateCoupon,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.IsActive,
		arg.ExpiresAt,
		arg.MinOrderAmount,
		arg.UsageLimit,
		arg.ID,
		arg.ShopID,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.IsActive,
		&i.ExpiresAt,
		&i.MinOrderAmount,
		&i.UsageLimit,
		&i.UsageCount,
	)
	return i, err
}

const validateCoupon = `-- name: ValidateCoupon :one
SELECT id, shop_id, code, type, value, is_active, expires_at, min_order_amount, usage_limit, usage_count FROM coupons
WHERE code = $1
  AND shop_id = $2
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
  AND (usage_limit IS NULL OR usage_count < usage_limit)
`

type ValidateCouponParams struct {
	Code   string      `json:"code"`
	ShopID pgtype.UUID `json:"shop_id"`
}

// Returns the coupon only when active, not expired, and under usage limit.
func (q *Queries) ValidateCoupon(ctx context.Context, arg ValidateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, validateCoupon, arg.Code, arg.ShopID)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.IsActive,
		&i.ExpiresAt,
		&i.MinOrderAmount,
		&i.UsageLimit,
		&i.UsageCount,
	)
	return i, err
}
