// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kb_articles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createKBArticle = `-- name: CreateKBArticle :one
INSERT INTO kb_articles (shop_id, category, title, slug, body, is_published, position)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, shop_id, category, title, slug, body, is_published, position, view_count, helpful_count, created_at, updated_at
`

type CreateKBArticleParams struct {
	ShopID      uuid.UUID `json:"shop_id"`
	Category    string    `json:"category"`
	Title       string    `json:"title"`
	Slug        string    `json:"slug"`
	Body        string    `json:"body"`
	IsPublished bool      `json:"is_published"`
	Position    int32     `json:"position"`
}

func (q *Queries) CreateKBArticle(ctx context.Context, arg CreateKBArticleParams) (KbArticle, error) {
	row := q.db.QueryRow(ctx, createKBArticle,
		arg.ShopID,
		arg.Category,
		arg.Title,
		arg.Slug,
		arg.Body,
		arg.IsPublished,
		arg.Position,
	)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Category,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.IsPublished,
		&i.Position,
		&i.ViewCount,
		&i.HelpfulCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKBArticle = `-- name: DeleteKBArticle :exec
DELETE FROM kb_articles WHERE id = $1 AND shop_id = $2
`

type DeleteKBArticleParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeleteKBArticle(ctx context.Context, arg DeleteKBArticleParams) error {
	_, err := q.db.Exec(ctx, deleteKBArticle, arg.ID, arg.ShopID)
	return err
}

const getKBArticleByID = `-- name: GetKBArticleByID :one
SELECT id, shop_id, category, title, slug, body, is_published, position, view_count, helpful_count, created_at, updated_at FROM kb_articles
WHERE id = $1 AND shop_id = $2
`

type GetKBArticleByIDParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) GetKBArticleByID(ctx context.Context, arg GetKBArticleByIDParams) (KbArticle, error) {
	row := q.db.QueryRow(ctx, getKBArticleByID, arg.ID, arg.ShopID)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Category,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.IsPublished,
		&i.Position,
		&i.ViewCount,
		&i.HelpfulCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKBArticleBySlug = `-- name: GetKBArticleBySlug :one
SELECT id, shop_id, category, title, slug, body, is_published, position, view_count, helpful_count, created_at, updated_at FROM kb_articles
WHERE shop_id = $1 AND slug = $2 AND is_published = true
`

type GetKBArticleBySlugParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Slug   string    `json:"slug"`
}

func (q *Queries) GetKBArticleBySlug(ctx context.Context, arg GetKBArticleBySlugParams) (KbArticle, error) {
	row := q.db.QueryRow(ctx, getKBArticleBySlug, arg.ShopID, arg.Slug)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Category,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.IsPublished,
		&i.Position,
		&i.ViewCount,
		&i.HelpfulCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementKBHelpfulCount = `-- name: IncrementKBHelpfulCount :exec
UPDATE kb_articles SET helpful_count = helpful_count + 1 WHERE id = $1
`

func (q *Queries) IncrementKBHelpfulCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementKBHelpfulCount, id)
	return err
}

const incrementKBViewCount = `-- name: IncrementKBViewCount :exec
UPDATE kb_articles SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementKBViewCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementKBViewCount, id)
	return err
}

const listKBArticles = `-- name: ListKBArticles :many
SELECT id, shop_id, category, title, slug, body, is_published, position, view_count, helpful_count, created_at, updated_at FROM kb_articles
WHERE shop_id = $1
  AND ($4::text IS NULL OR category = $4)
  AND ($5::boolean IS NULL OR is_published = $5)
ORDER BY position ASC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListKBArticlesParams struct {
	ShopID        uuid.UUID   `json:"shop_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
	Category      pgtype.Text `json:"category"`
	PublishedOnly pgtype.Bool `json:"published_only"`
}

func (q *Queries) ListKBArticles(ctx context.Context, arg ListKBArticlesParams) ([]KbArticle, error) {
	rows, err := q.db.Query(ctx, listKBArticles,
		arg.ShopID,
		arg.Limit,
		arg.Offset,
		arg.Category,
		arg.PublishedOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbArticle
	for rows.Next() {
		var i KbArticle
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Category,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.IsPublished,
			&i.Position,
			&i.ViewCount,
			&i.HelpfulCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKBArticle = `-- name: UpdateKBArticle :one
UPDATE kb_articles SET
    category     = COALESCE($3, category),
    title        = COALESCE($4, title),
    slug         = COALESCE($5, slug),
    body         = COALESCE($6, body),
    is_published = COALESCE($7, is_published),
    position     = COALESCE($8, position),
    updated_at   = NOW()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, category, title, slug, body, is_published, position, view_count, helpful_count, created_at, updated_at
`

type UpdateKBArticleParams struct {
	ID          uuid.UUID   `json:"id"`
	ShopID      uuid.UUID   `json:"shop_id"`
	Category    pgtype.Text `json:"category"`
	Title       pgtype.Text `json:"title"`
	Slug        pgtype.Text `json:"slug"`
	Body        pgtype.Text `json:"body"`
	IsPublished pgtype.Bool `json:"is_published"`
	Position    pgtype.Int4 `json:"position"`
}

func (q *Queries) UpdateKBArticle(ctx context.Context, arg UpdateKBArticleParams) (KbArticle, error) {
	row := q.db.QueryRow(ctx, updateKBArticle,
		arg.ID,
		arg.ShopID,
		arg.Category,
		arg.Title,
		arg.Slug,
		arg.Body,
		arg.IsPublished,
		arg.Position,
	)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Category,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.IsPublished,
		&i.Position,
		&i.ViewCount,
		&i.HelpfulCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
