// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loyalty_tiers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLoyaltyTier = `-- name: CreateLoyaltyTier :one

INSERT INTO loyalty_tiers (shop_id, name, min_lifetime_points, benefits, badge_label, badge_color, position)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, shop_id, name, min_lifetime_points, benefits, badge_label, badge_color, position, created_at
`

type CreateLoyaltyTierParams struct {
	ShopID            uuid.UUID   `json:"shop_id"`
	Name              string      `json:"name"`
	MinLifetimePoints int64       `json:"min_lifetime_points"`
	Benefits          []byte      `json:"benefits"`
	BadgeLabel        pgtype.Text `json:"badge_label"`
	BadgeColor        pgtype.Text `json:"badge_color"`
	Position          int32       `json:"position"`
}

// ==================== Loyalty Tiers ====================
func (q *Queries) CreateLoyaltyTier(ctx context.Context, arg CreateLoyaltyTierParams) (LoyaltyTier, error) {
	row := q.db.QueryRow(ctx, createLoyaltyTier,
		arg.ShopID,
		arg.Name,
		arg.MinLifetimePoints,
		arg.Benefits,
		arg.BadgeLabel,
		arg.BadgeColor,
		arg.Position,
	)
	var i LoyaltyTier
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.MinLifetimePoints,
		&i.Benefits,
		&i.BadgeLabel,
		&i.BadgeColor,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLoyaltyTier = `-- name: DeleteLoyaltyTier :exec
DELETE FROM loyalty_tiers WHERE id = $1 AND shop_id = $2
`

type DeleteLoyaltyTierParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeleteLoyaltyTier(ctx context.Context, arg DeleteLoyaltyTierParams) error {
	_, err := q.db.Exec(ctx, deleteLoyaltyTier, arg.ID, arg.ShopID)
	return err
}

const getCustomerCurrentTier = `-- name: GetCustomerCurrentTier :one
SELECT lt.id, lt.shop_id, lt.name, lt.min_lifetime_points, lt.benefits, lt.badge_label, lt.badge_color, lt.position, lt.created_at
FROM loyalty_tiers lt
JOIN loyalty_accounts la ON la.shop_id = lt.shop_id
WHERE la.shop_id = $1
  AND la.customer_id = $2
  AND lt.min_lifetime_points <= la.lifetime_points
ORDER BY lt.min_lifetime_points DESC
LIMIT 1
`

type GetCustomerCurrentTierParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) GetCustomerCurrentTier(ctx context.Context, arg GetCustomerCurrentTierParams) (LoyaltyTier, error) {
	row := q.db.QueryRow(ctx, getCustomerCurrentTier, arg.ShopID, arg.CustomerID)
	var i LoyaltyTier
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.MinLifetimePoints,
		&i.Benefits,
		&i.BadgeLabel,
		&i.BadgeColor,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getLoyaltyLeaderboard = `-- name: GetLoyaltyLeaderboard :many
SELECT la.customer_id, la.points_balance, la.lifetime_points
FROM loyalty_accounts la
WHERE la.shop_id = $1
ORDER BY la.points_balance DESC
LIMIT $2
`

type GetLoyaltyLeaderboardParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Limit  int32     `json:"limit"`
}

type GetLoyaltyLeaderboardRow struct {
	CustomerID     uuid.UUID `json:"customer_id"`
	PointsBalance  int32     `json:"points_balance"`
	LifetimePoints int32     `json:"lifetime_points"`
}

func (q *Queries) GetLoyaltyLeaderboard(ctx context.Context, arg GetLoyaltyLeaderboardParams) ([]GetLoyaltyLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLoyaltyLeaderboard, arg.ShopID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLoyaltyLeaderboardRow
	for rows.Next() {
		var i GetLoyaltyLeaderboardRow
		if err := rows.Scan(&i.CustomerID, &i.PointsBalance, &i.LifetimePoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoyaltyTier = `-- name: GetLoyaltyTier :one
SELECT id, shop_id, name, min_lifetime_points, benefits, badge_label, badge_color, position, created_at FROM loyalty_tiers WHERE id = $1 AND shop_id = $2
`

type GetLoyaltyTierParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) GetLoyaltyTier(ctx context.Context, arg GetLoyaltyTierParams) (LoyaltyTier, error) {
	row := q.db.QueryRow(ctx, getLoyaltyTier, arg.ID, arg.ShopID)
	var i LoyaltyTier
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.MinLifetimePoints,
		&i.Benefits,
		&i.BadgeLabel,
		&i.BadgeColor,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getNextTier = `-- name: GetNextTier :one
SELECT lt.id, lt.shop_id, lt.name, lt.min_lifetime_points, lt.benefits, lt.badge_label, lt.badge_color, lt.position, lt.created_at
FROM loyalty_tiers lt
JOIN loyalty_accounts la ON la.shop_id = lt.shop_id
WHERE la.shop_id = $1
  AND la.customer_id = $2
  AND lt.min_lifetime_points > la.lifetime_points
ORDER BY lt.min_lifetime_points ASC
LIMIT 1
`

type GetNextTierParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) GetNextTier(ctx context.Context, arg GetNextTierParams) (LoyaltyTier, error) {
	row := q.db.QueryRow(ctx, getNextTier, arg.ShopID, arg.CustomerID)
	var i LoyaltyTier
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.MinLifetimePoints,
		&i.Benefits,
		&i.BadgeLabel,
		&i.BadgeColor,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listLoyaltyTiers = `-- name: ListLoyaltyTiers :many
SELECT id, shop_id, name, min_lifetime_points, benefits, badge_label, badge_color, position, created_at FROM loyalty_tiers
WHERE shop_id = $1
ORDER BY position ASC
`

func (q *Queries) ListLoyaltyTiers(ctx context.Context, shopID uuid.UUID) ([]LoyaltyTier, error) {
	rows, err := q.db.Query(ctx, listLoyaltyTiers, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoyaltyTier
	for rows.Next() {
		var i LoyaltyTier
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.MinLifetimePoints,
			&i.Benefits,
			&i.BadgeLabel,
			&i.BadgeColor,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoyaltyTier = `-- name: UpdateLoyaltyTier :one
UPDATE loyalty_tiers SET
    name                = COALESCE($1, name),
    min_lifetime_points = COALESCE($2, min_lifetime_points),
    benefits            = COALESCE($3, benefits),
    badge_label         = COALESCE($4, badge_label),
    badge_color         = COALESCE($5, badge_color),
    position            = COALESCE($6, position)
WHERE id = $7 AND shop_id = $8
RETURNING id, shop_id, name, min_lifetime_points, benefits, badge_label, badge_color, position, created_at
`

type UpdateLoyaltyTierParams struct {
	Name              pgtype.Text `json:"name"`
	MinLifetimePoints pgtype.Int8 `json:"min_lifetime_points"`
	Benefits          []byte      `json:"benefits"`
	BadgeLabel        pgtype.Text `json:"badge_label"`
	BadgeColor        pgtype.Text `json:"badge_color"`
	Position          pgtype.Int4 `json:"position"`
	ID                uuid.UUID   `json:"id"`
	ShopID            uuid.UUID   `json:"shop_id"`
}

func (q *Queries) UpdateLoyaltyTier(ctx context.Context, arg UpdateLoyaltyTierParams) (LoyaltyTier, error) {
	row := q.db.QueryRow(ctx, updateLoyaltyTier,
		arg.Name,
		arg.MinLifetimePoints,
		arg.Benefits,
		arg.BadgeLabel,
		arg.BadgeColor,
		arg.Position,
		arg.ID,
		arg.ShopID,
	)
	var i LoyaltyTier
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.MinLifetimePoints,
		&i.Benefits,
		&i.BadgeLabel,
		&i.BadgeColor,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
