// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFlashSaleItem(ctx context.Context, arg AddFlashSaleItemParams) (FlashSaleItem, error)
	// ==================== Wishlists ====================
	AddToWishlist(ctx context.Context, arg AddToWishlistParams) (Wishlist, error)
	AdjustInventoryLevel(ctx context.Context, arg AdjustInventoryLevelParams) (InventoryLevel, error)
	AdminListShops(ctx context.Context, arg AdminListShopsParams) ([]AdminListShopsRow, error)
	AssignSupportTicket(ctx context.Context, arg AssignSupportTicketParams) (SupportTicket, error)
	ClearDefaultAddresses(ctx context.Context, arg ClearDefaultAddressesParams) error
	CloseSupportTicket(ctx context.Context, arg CloseSupportTicketParams) (SupportTicket, error)
	ConcludeABTest(ctx context.Context, arg ConcludeABTestParams) error
	CountAIUsage(ctx context.Context, arg CountAIUsageParams) (int64, error)
	CountActiveFlashSales(ctx context.Context, shopID uuid.UUID) (int64, error)
	CountCategories(ctx context.Context, shopID pgtype.UUID) (int64, error)
	CountCustomerAddresses(ctx context.Context, arg CountCustomerAddressesParams) (int64, error)
	CountCustomers(ctx context.Context, shopID pgtype.UUID) (int64, error)
	CountNewShops(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	CountOrders(ctx context.Context, shopID uuid.UUID) (int64, error)
	CountOrdersByStatus(ctx context.Context, arg CountOrdersByStatusParams) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountProductsForSEOAudit(ctx context.Context, shopID pgtype.UUID) (int64, error)
	CountRedirects(ctx context.Context, shopID uuid.UUID) (int64, error)
	CountReferralConversionsByReferrer(ctx context.Context, arg CountReferralConversionsByReferrerParams) (int64, error)
	CountReturns(ctx context.Context, shopID uuid.UUID) (int64, error)
	CountShopInvoices(ctx context.Context, shopID pgtype.UUID) (int64, error)
	CountShopStaff(ctx context.Context, shopID pgtype.UUID) (int64, error)
	CountShops(ctx context.Context) (int64, error)
	CountShopsByStatus(ctx context.Context, status NullShopStatus) (int64, error)
	CountStaffByRole(ctx context.Context, roleID pgtype.UUID) (int64, error)
	CountSupportTickets(ctx context.Context, shopID pgtype.UUID) (int64, error)
	CountSupportTicketsByStatus(ctx context.Context, arg CountSupportTicketsByStatusParams) (int64, error)
	CountUnreadMessages(ctx context.Context, arg CountUnreadMessagesParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountVariantsByProduct(ctx context.Context, arg CountVariantsByProductParams) (int64, error)
	CreateABTest(ctx context.Context, arg CreateABTestParams) (AbTest, error)
	// ==================== Audit Logs ====================
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	// ==================== Categories ====================
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateConsentLog(ctx context.Context, arg CreateConsentLogParams) (ConsentLog, error)
	// ==================== Coupons ====================
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	// ==================== Customers ====================
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateCustomerAddress(ctx context.Context, arg CreateCustomerAddressParams) (CustomerAddress, error)
	CreateFlashSale(ctx context.Context, arg CreateFlashSaleParams) (FlashSale, error)
	// ==================== Product Images ====================
	CreateImage(ctx context.Context, arg CreateImageParams) (ProductImage, error)
	// ==================== Invitations ====================
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateKBArticle(ctx context.Context, arg CreateKBArticleParams) (KbArticle, error)
	// ==================== Loyalty Tiers ====================
	CreateLoyaltyTier(ctx context.Context, arg CreateLoyaltyTierParams) (LoyaltyTier, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// ==================== Orders ====================
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	// ==================== Order Items ====================
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	// ==================== Plans ====================
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	// ==================== Platform Admins ====================
	CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error)
	// ==================== Products ====================
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// ==================== SEO ====================
	// ── URL Redirects ─────────────────────────────────────────────────────────────
	CreateRedirect(ctx context.Context, arg CreateRedirectParams) (UrlRedirect, error)
	CreateReferralCode(ctx context.Context, arg CreateReferralCodeParams) (ReferralCode, error)
	// ==================== Order Returns ====================
	CreateReturn(ctx context.Context, arg CreateReturnParams) (OrderReturn, error)
	// ==================== Product Reviews ====================
	CreateReview(ctx context.Context, arg CreateReviewParams) (ProductReview, error)
	// ==================== Shipping Rates ====================
	CreateShippingRate(ctx context.Context, arg CreateShippingRateParams) (ShippingRate, error)
	// ==================== Shipping Zones ====================
	CreateShippingZone(ctx context.Context, arg CreateShippingZoneParams) (ShippingZone, error)
	// ==================== Shops ====================
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	// ==================== Shop Invoices ====================
	CreateShopInvoice(ctx context.Context, arg CreateShopInvoiceParams) (ShopInvoice, error)
	// ==================== Shop Payment Methods ====================
	CreateShopPaymentMethod(ctx context.Context, arg CreateShopPaymentMethodParams) (ShopPaymentMethod, error)
	// ==================== Shop Roles ====================
	CreateShopRole(ctx context.Context, arg CreateShopRoleParams) (ShopRole, error)
	// ==================== Shop Staff ====================
	CreateShopStaff(ctx context.Context, arg CreateShopStaffParams) (ShopStaff, error)
	// ==================== Staff Audit Log ====================
	CreateStaffAuditLog(ctx context.Context, arg CreateStaffAuditLogParams) (StaffAuditLog, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateSubscriptionOrder(ctx context.Context, arg CreateSubscriptionOrderParams) (SubscriptionOrder, error)
	// sql/queries/subscriptions.sql
	CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error)
	// ==================== Support Automation Rules ====================
	CreateSupportAutomationRule(ctx context.Context, arg CreateSupportAutomationRuleParams) (SupportAutomationRule, error)
	// ==================== Support Messages ====================
	CreateSupportMessage(ctx context.Context, arg CreateSupportMessageParams) (SupportMessage, error)
	// ==================== Support Tickets ====================
	CreateSupportTicket(ctx context.Context, arg CreateSupportTicketParams) (SupportTicket, error)
	CreateTieredDiscount(ctx context.Context, arg CreateTieredDiscountParams) (TieredDiscount, error)
	// ==================== Users ====================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// ==================== User Secrets ====================
	CreateUserSecrets(ctx context.Context, arg CreateUserSecretsParams) (UserSecret, error)
	// ==================== Product Variants ====================
	CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error)
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error)
	// ==================== Webhooks ====================
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	CustomerHasPurchasedProduct(ctx context.Context, arg CustomerHasPurchasedProductParams) (bool, error)
	// Atomically decrements stock only when sufficient units are available.
	// Returns the updated row; returns no rows when stock is insufficient.
	DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (DecrementProductStockRow, error)
	// Atomically decrements variant stock only when sufficient units are available.
	DecrementVariantStock(ctx context.Context, arg DecrementVariantStockParams) (DecrementVariantStockRow, error)
	DeleteAuditLogsBefore(ctx context.Context, arg DeleteAuditLogsBeforeParams) error
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteCoupon(ctx context.Context, arg DeleteCouponParams) error
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error
	DeleteCustomerAddress(ctx context.Context, arg DeleteCustomerAddressParams) error
	DeleteExpiredInvitations(ctx context.Context) error
	DeleteFlashSale(ctx context.Context, arg DeleteFlashSaleParams) error
	DeleteImage(ctx context.Context, arg DeleteImageParams) error
	DeleteImagesByProduct(ctx context.Context, arg DeleteImagesByProductParams) error
	DeleteInvitation(ctx context.Context, id uuid.UUID) error
	DeleteKBArticle(ctx context.Context, arg DeleteKBArticleParams) error
	DeleteLoyaltyTier(ctx context.Context, arg DeleteLoyaltyTierParams) error
	DeleteOldNotifications(ctx context.Context, shopID uuid.UUID) error
	DeleteOrder(ctx context.Context, arg DeleteOrderParams) error
	DeleteOrderItem(ctx context.Context, id uuid.UUID) error
	DeleteOrderItemsByOrder(ctx context.Context, orderID pgtype.UUID) error
	DeletePlan(ctx context.Context, id uuid.UUID) error
	DeletePlatformAdmin(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteProductAttribute(ctx context.Context, arg DeleteProductAttributeParams) error
	DeleteProductAttributes(ctx context.Context, productID uuid.UUID) error
	DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error
	DeleteRedirect(ctx context.Context, arg DeleteRedirectParams) error
	DeleteSavedCart(ctx context.Context, arg DeleteSavedCartParams) error
	DeleteShippingRate(ctx context.Context, arg DeleteShippingRateParams) error
	DeleteShippingZone(ctx context.Context, arg DeleteShippingZoneParams) error
	DeleteShop(ctx context.Context, id uuid.UUID) error
	DeleteShopInvoice(ctx context.Context, id uuid.UUID) error
	DeleteShopPaymentMethod(ctx context.Context, arg DeleteShopPaymentMethodParams) error
	DeleteShopRole(ctx context.Context, id uuid.UUID) error
	DeleteShopStaff(ctx context.Context, id uuid.UUID) error
	DeleteShopStaffProtected(ctx context.Context, arg DeleteShopStaffProtectedParams) error
	DeleteSubscriptionPlan(ctx context.Context, arg DeleteSubscriptionPlanParams) error
	DeleteSupportAutomationRule(ctx context.Context, arg DeleteSupportAutomationRuleParams) error
	DeleteSupportMessage(ctx context.Context, id uuid.UUID) error
	DeleteSupportTicket(ctx context.Context, arg DeleteSupportTicketParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSecrets(ctx context.Context, userID uuid.UUID) error
	DeleteVariant(ctx context.Context, arg DeleteVariantParams) error
	DeleteVariantsByProduct(ctx context.Context, arg DeleteVariantsByProductParams) error
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error
	Disable2FA(ctx context.Context, userID uuid.UUID) error
	Enable2FA(ctx context.Context, arg Enable2FAParams) error
	// Find the cheapest active rate whose zone covers the given country code.
	FindRateByCountry(ctx context.Context, arg FindRateByCountryParams) (ShippingRate, error)
	GetABTest(ctx context.Context, arg GetABTestParams) (AbTest, error)
	// ==================== AI Config ====================
	GetAIConfig(ctx context.Context) (AiConfig, error)
	GetAccountsWithExpiredPoints(ctx context.Context) ([]GetAccountsWithExpiredPointsRow, error)
	GetActiveCurrencies(ctx context.Context) ([]Currency, error)
	GetActiveFlashSales(ctx context.Context, shopID uuid.UUID) ([]FlashSale, error)
	GetActiveReorderRules(ctx context.Context, shopID uuid.UUID) ([]ReorderRule, error)
	GetActiveTieredDiscount(ctx context.Context, arg GetActiveTieredDiscountParams) (TieredDiscount, error)
	GetAllProductsForSEOAudit(ctx context.Context, shopID pgtype.UUID) ([]GetAllProductsForSEOAuditRow, error)
	GetAtRiskCustomers(ctx context.Context, arg GetAtRiskCustomersParams) ([]GetAtRiskCustomersRow, error)
	GetAttributesByShop(ctx context.Context, shopID uuid.UUID) ([]GetAttributesByShopRow, error)
	GetAuditLog(ctx context.Context, id uuid.UUID) (AuditLog, error)
	GetBillingSummary(ctx context.Context) (GetBillingSummaryRow, error)
	GetCartByRecoveryToken(ctx context.Context, recoveryToken pgtype.Text) (GetCartByRecoveryTokenRow, error)
	GetCartRecoveryStats(ctx context.Context, arg GetCartRecoveryStatsParams) (GetCartRecoveryStatsRow, error)
	// Carts idle for 1-2 hours, email_1 not yet sent, not recovered.
	GetCartsForEmail1(ctx context.Context) ([]GetCartsForEmail1Row, error)
	// Carts idle 23-25 hours after email_1 was sent, email_2 not yet sent.
	GetCartsForEmail2(ctx context.Context) ([]GetCartsForEmail2Row, error)
	// Carts where email_2 was sent 71-73 hours ago, email_3 not yet sent.
	GetCartsForEmail3(ctx context.Context) ([]GetCartsForEmail3Row, error)
	GetCategoriesForSitemap(ctx context.Context, shopID pgtype.UUID) ([]GetCategoriesForSitemapRow, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (Category, error)
	GetCopurchasedProducts(ctx context.Context, arg GetCopurchasedProductsParams) ([]GetCopurchasedProductsRow, error)
	GetCoupon(ctx context.Context, arg GetCouponParams) (Coupon, error)
	GetCouponByCode(ctx context.Context, arg GetCouponByCodeParams) (Coupon, error)
	GetCustomer(ctx context.Context, arg GetCustomerParams) (Customer, error)
	GetCustomerAddress(ctx context.Context, arg GetCustomerAddressParams) (CustomerAddress, error)
	GetCustomerByEmail(ctx context.Context, arg GetCustomerByEmailParams) (Customer, error)
	GetCustomerCurrentTier(ctx context.Context, arg GetCustomerCurrentTierParams) (LoyaltyTier, error)
	GetCustomerNotifPrefs(ctx context.Context, customerID uuid.UUID) (CustomerNotificationPref, error)
	GetCustomerOrderSummary(ctx context.Context, arg GetCustomerOrderSummaryParams) (GetCustomerOrderSummaryRow, error)
	GetDueSubscriptions(ctx context.Context) ([]GetDueSubscriptionsRow, error)
	GetDynamicDropoffs(ctx context.Context, arg GetDynamicDropoffsParams) ([]GetDynamicDropoffsRow, error)
	GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (pgtype.Numeric, error)
	GetFailedSubscriptionOrders(ctx context.Context) ([]GetFailedSubscriptionOrdersRow, error)
	GetFlashSaleByID(ctx context.Context, arg GetFlashSaleByIDParams) (FlashSale, error)
	GetFlashSalePrice(ctx context.Context, arg GetFlashSalePriceParams) (int32, error)
	GetImage(ctx context.Context, arg GetImageParams) (ProductImage, error)
	GetImagesByProductIDs(ctx context.Context, arg GetImagesByProductIDsParams) ([]ProductImage, error)
	GetInventoryLevel(ctx context.Context, arg GetInventoryLevelParams) (InventoryLevel, error)
	GetInventoryLevelsByVariant(ctx context.Context, arg GetInventoryLevelsByVariantParams) ([]InventoryLevel, error)
	GetInvitation(ctx context.Context, id uuid.UUID) (Invitation, error)
	GetInvitationByToken(ctx context.Context, token string) (Invitation, error)
	GetKBArticleByID(ctx context.Context, arg GetKBArticleByIDParams) (KbArticle, error)
	GetKBArticleBySlug(ctx context.Context, arg GetKBArticleBySlugParams) (KbArticle, error)
	GetLowStockVariants(ctx context.Context, shopID uuid.UUID) ([]GetLowStockVariantsRow, error)
	GetLoyaltyAccount(ctx context.Context, arg GetLoyaltyAccountParams) (LoyaltyAccount, error)
	GetLoyaltyLeaderboard(ctx context.Context, arg GetLoyaltyLeaderboardParams) ([]GetLoyaltyLeaderboardRow, error)
	GetLoyaltyProgram(ctx context.Context, shopID uuid.UUID) (LoyaltyProgram, error)
	GetLoyaltyTier(ctx context.Context, arg GetLoyaltyTierParams) (LoyaltyTier, error)
	GetLoyaltyTransactions(ctx context.Context, arg GetLoyaltyTransactionsParams) ([]LoyaltyTransaction, error)
	GetMostWishlistedProducts(ctx context.Context, arg GetMostWishlistedProductsParams) ([]GetMostWishlistedProductsRow, error)
	GetMyReferrals(ctx context.Context, arg GetMyReferralsParams) ([]GetMyReferralsRow, error)
	GetNextOrderNumber(ctx context.Context, shopID uuid.UUID) (int32, error)
	GetNextTier(ctx context.Context, arg GetNextTierParams) (LoyaltyTier, error)
	GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]Notification, error)
	GetOrder(ctx context.Context, arg GetOrderParams) (Order, error)
	GetOrderByNumber(ctx context.Context, arg GetOrderByNumberParams) (Order, error)
	GetOrderItem(ctx context.Context, id uuid.UUID) (OrderItem, error)
	GetPendingReviews(ctx context.Context, arg GetPendingReviewsParams) ([]GetPendingReviewsRow, error)
	GetPlan(ctx context.Context, id uuid.UUID) (Plan, error)
	GetPlanByName(ctx context.Context, name string) (Plan, error)
	GetPlanDistribution(ctx context.Context) ([]GetPlanDistributionRow, error)
	GetPlatformAdmin(ctx context.Context, id uuid.UUID) (PlatformAdmin, error)
	GetPlatformAdminByEmail(ctx context.Context, email string) (PlatformAdmin, error)
	GetPopularFilters(ctx context.Context, shopID uuid.UUID) ([]GetPopularFiltersRow, error)
	GetProduct(ctx context.Context, arg GetProductParams) (Product, error)
	GetProductBundleComponents(ctx context.Context, arg GetProductBundleComponentsParams) ([]ProductBundle, error)
	GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (Product, error)
	GetProductBySlug(ctx context.Context, arg GetProductBySlugParams) (Product, error)
	GetProductsForSEOAudit(ctx context.Context, arg GetProductsForSEOAuditParams) ([]GetProductsForSEOAuditRow, error)
	// ── Sitemap ───────────────────────────────────────────────────────────────────
	GetProductsForSitemap(ctx context.Context, shopID pgtype.UUID) ([]GetProductsForSitemapRow, error)
	GetPushSubscriptions(ctx context.Context, arg GetPushSubscriptionsParams) ([]PushSubscription, error)
	GetRecentSocialProofEvents(ctx context.Context, arg GetRecentSocialProofEventsParams) ([]GetRecentSocialProofEventsRow, error)
	GetRedirect(ctx context.Context, arg GetRedirectParams) (UrlRedirect, error)
	GetReferralCode(ctx context.Context, arg GetReferralCodeParams) (ReferralCode, error)
	GetReferralCodeByCode(ctx context.Context, arg GetReferralCodeByCodeParams) (ReferralCode, error)
	// ==================== Referral Config ====================
	GetReferralConfig(ctx context.Context, shopID uuid.UUID) (ReferralConfig, error)
	GetReferralStats(ctx context.Context, shopID uuid.UUID) (GetReferralStatsRow, error)
	GetReturn(ctx context.Context, arg GetReturnParams) (OrderReturn, error)
	GetReview(ctx context.Context, arg GetReviewParams) (ProductReview, error)
	GetReviewSummary(ctx context.Context, arg GetReviewSummaryParams) (GetReviewSummaryRow, error)
	GetReviewsByProduct(ctx context.Context, arg GetReviewsByProductParams) ([]GetReviewsByProductRow, error)
	GetSavedCart(ctx context.Context, arg GetSavedCartParams) (SavedCart, error)
	GetSearchFacets(ctx context.Context, shopID uuid.UUID) ([]GetSearchFacetsRow, error)
	GetShippingRate(ctx context.Context, arg GetShippingRateParams) (ShippingRate, error)
	GetShippingZone(ctx context.Context, arg GetShippingZoneParams) (ShippingZone, error)
	GetShop(ctx context.Context, id uuid.UUID) (Shop, error)
	GetShopByCustomDomain(ctx context.Context, customDomain pgtype.Text) (Shop, error)
	GetShopBySubdomain(ctx context.Context, subdomain string) (Shop, error)
	GetShopCurrencySettings(ctx context.Context, id uuid.UUID) (GetShopCurrencySettingsRow, error)
	GetShopInvoice(ctx context.Context, id uuid.UUID) (ShopInvoice, error)
	GetShopNotificationPrefs(ctx context.Context, id uuid.UUID) ([]byte, error)
	GetShopOwner(ctx context.Context, shopID pgtype.UUID) (ShopStaff, error)
	GetShopPaymentMethod(ctx context.Context, arg GetShopPaymentMethodParams) (ShopPaymentMethod, error)
	GetShopPaymentMethodByProvider(ctx context.Context, arg GetShopPaymentMethodByProviderParams) (ShopPaymentMethod, error)
	GetShopPlanName(ctx context.Context, id uuid.UUID) (string, error)
	GetShopRole(ctx context.Context, id uuid.UUID) (ShopRole, error)
	GetShopStaff(ctx context.Context, id uuid.UUID) (ShopStaff, error)
	GetShopStaffByUserAndShop(ctx context.Context, arg GetShopStaffByUserAndShopParams) (ShopStaff, error)
	GetStockMovements(ctx context.Context, arg GetStockMovementsParams) ([]StockMovement, error)
	GetSubscription(ctx context.Context, arg GetSubscriptionParams) (GetSubscriptionRow, error)
	GetSubscriptionPlan(ctx context.Context, arg GetSubscriptionPlanParams) (SubscriptionPlan, error)
	GetSupportAutomationRule(ctx context.Context, arg GetSupportAutomationRuleParams) (SupportAutomationRule, error)
	GetSupportMessage(ctx context.Context, id uuid.UUID) (SupportMessage, error)
	GetSupportTicket(ctx context.Context, arg GetSupportTicketParams) (SupportTicket, error)
	GetTieredDiscounts(ctx context.Context, shopID uuid.UUID) ([]TieredDiscount, error)
	GetTotalRevenue(ctx context.Context, shopID uuid.UUID) (pgtype.Numeric, error)
	GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int64, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserSecrets(ctx context.Context, userID uuid.UUID) (UserSecret, error)
	GetVariant(ctx context.Context, arg GetVariantParams) (ProductVariant, error)
	GetVariantsByProductIDs(ctx context.Context, arg GetVariantsByProductIDsParams) ([]ProductVariant, error)
	GetWarehouses(ctx context.Context, shopID uuid.UUID) ([]Warehouse, error)
	GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error)
	GetWishlist(ctx context.Context, arg GetWishlistParams) ([]GetWishlistRow, error)
	GetWishlistedCustomersForProduct(ctx context.Context, arg GetWishlistedCustomersForProductParams) ([]GetWishlistedCustomersForProductRow, error)
	HasOrderSinceSavedCart(ctx context.Context, arg HasOrderSinceSavedCartParams) (bool, error)
	IncrementCouponUsage(ctx context.Context, arg IncrementCouponUsageParams) (int32, error)
	IncrementHelpfulCount(ctx context.Context, arg IncrementHelpfulCountParams) error
	IncrementKBHelpfulCount(ctx context.Context, id uuid.UUID) error
	IncrementKBViewCount(ctx context.Context, id uuid.UUID) error
	IncrementRedirectHitCount(ctx context.Context, arg IncrementRedirectHitCountParams) error
	IncrementReferralCodeUses(ctx context.Context, id uuid.UUID) error
	InsertAIUsageLog(ctx context.Context, arg InsertAIUsageLogParams) error
	InsertAnalyticsEvent(ctx context.Context, arg InsertAnalyticsEventParams) (AnalyticsEvent, error)
	// ==================== Social Proof ====================
	InsertSocialProofEvent(ctx context.Context, arg InsertSocialProofEventParams) error
	IsWishlisted(ctx context.Context, arg IsWishlistedParams) (bool, error)
	ListABTestsByShop(ctx context.Context, shopID uuid.UUID) ([]AbTest, error)
	ListABTestsForAutoConclusion(ctx context.Context) ([]AbTest, error)
	ListActiveABTests(ctx context.Context, shopID uuid.UUID) ([]AbTest, error)
	ListActiveCoupons(ctx context.Context, shopID pgtype.UUID) ([]Coupon, error)
	ListActiveSupportAutomationRules(ctx context.Context, shopID pgtype.UUID) ([]SupportAutomationRule, error)
	ListActiveWebhooks(ctx context.Context, shopID pgtype.UUID) ([]Webhook, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error)
	ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error)
	ListAuditLogsByResourceID(ctx context.Context, arg ListAuditLogsByResourceIDParams) ([]AuditLog, error)
	ListCategories(ctx context.Context, shopID pgtype.UUID) ([]Category, error)
	ListConsentsByCustomer(ctx context.Context, customerID uuid.UUID) ([]ConsentLog, error)
	ListCoupons(ctx context.Context, shopID pgtype.UUID) ([]Coupon, error)
	// ==================== Customer Addresses ====================
	ListCustomerAddresses(ctx context.Context, arg ListCustomerAddressesParams) ([]CustomerAddress, error)
	ListCustomerSubscriptions(ctx context.Context, arg ListCustomerSubscriptionsParams) ([]ListCustomerSubscriptionsRow, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListDeletedCustomers(ctx context.Context, shopID pgtype.UUID) ([]Customer, error)
	ListDeletedProducts(ctx context.Context, shopID pgtype.UUID) ([]Product, error)
	ListEnabledPaymentMethods(ctx context.Context, shopID pgtype.UUID) ([]ShopPaymentMethod, error)
	ListImagesByProduct(ctx context.Context, arg ListImagesByProductParams) ([]ProductImage, error)
	ListImagesByVariant(ctx context.Context, arg ListImagesByVariantParams) ([]ProductImage, error)
	ListInternalNotes(ctx context.Context, ticketID pgtype.UUID) ([]SupportMessage, error)
	ListInvitationsByEmail(ctx context.Context, email string) ([]Invitation, error)
	ListInvitationsByInviter(ctx context.Context, invitedByUserID pgtype.UUID) ([]Invitation, error)
	ListKBArticles(ctx context.Context, arg ListKBArticlesParams) ([]KbArticle, error)
	ListLoyaltyTiers(ctx context.Context, shopID uuid.UUID) ([]LoyaltyTier, error)
	ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]Order, error)
	ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error)
	ListPlans(ctx context.Context) ([]Plan, error)
	ListPlatformAdmins(ctx context.Context) ([]PlatformAdmin, error)
	ListProductAttributes(ctx context.Context, productID uuid.UUID) ([]ProductAttribute, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	// Keyset pagination ordered by (created_at DESC, id DESC).
	// Pass cursor_created_at + cursor_id from the last row to get the next page.
	// Leave them NULL to get the first page.
	ListProductsCursor(ctx context.Context, arg ListProductsCursorParams) ([]Product, error)
	ListPublicSupportMessages(ctx context.Context, ticketID pgtype.UUID) ([]SupportMessage, error)
	ListRatesByZone(ctx context.Context, arg ListRatesByZoneParams) ([]ShippingRate, error)
	ListRedirects(ctx context.Context, arg ListRedirectsParams) ([]UrlRedirect, error)
	ListReturns(ctx context.Context, arg ListReturnsParams) ([]OrderReturn, error)
	ListReturnsByOrder(ctx context.Context, arg ListReturnsByOrderParams) ([]OrderReturn, error)
	ListRootCategories(ctx context.Context, shopID pgtype.UUID) ([]Category, error)
	ListShippingRates(ctx context.Context, shopID uuid.UUID) ([]ShippingRate, error)
	ListShippingZones(ctx context.Context, shopID pgtype.UUID) ([]ShippingZone, error)
	ListShopInvoices(ctx context.Context, arg ListShopInvoicesParams) ([]ShopInvoice, error)
	ListShopInvoicesByStatus(ctx context.Context, arg ListShopInvoicesByStatusParams) ([]ShopInvoice, error)
	ListShopPaymentMethods(ctx context.Context, shopID pgtype.UUID) ([]ShopPaymentMethod, error)
	ListShopRoles(ctx context.Context, shopID pgtype.UUID) ([]ShopRole, error)
	ListShopStaff(ctx context.Context, shopID pgtype.UUID) ([]ShopStaff, error)
	ListShopSubscriptions(ctx context.Context, arg ListShopSubscriptionsParams) ([]ListShopSubscriptionsRow, error)
	ListShops(ctx context.Context, arg ListShopsParams) ([]Shop, error)
	ListShopsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Shop, error)
	ListShopsByStatus(ctx context.Context, status NullShopStatus) ([]Shop, error)
	ListShopsForUser(ctx context.Context, userID pgtype.UUID) ([]ListShopsForUserRow, error)
	ListStaffAuditLog(ctx context.Context, arg ListStaffAuditLogParams) ([]StaffAuditLog, error)
	ListStaffByUser(ctx context.Context, userID pgtype.UUID) ([]ShopStaff, error)
	ListStaffWithUsers(ctx context.Context, shopID pgtype.UUID) ([]ListStaffWithUsersRow, error)
	ListSubcategories(ctx context.Context, arg ListSubcategoriesParams) ([]Category, error)
	ListSubscriptionPlans(ctx context.Context, shopID uuid.UUID) ([]SubscriptionPlan, error)
	ListSupportAutomationRules(ctx context.Context, shopID pgtype.UUID) ([]SupportAutomationRule, error)
	ListSupportMessages(ctx context.Context, ticketID pgtype.UUID) ([]SupportMessage, error)
	ListSupportTickets(ctx context.Context, arg ListSupportTicketsParams) ([]SupportTicket, error)
	ListSupportTicketsByCustomer(ctx context.Context, arg ListSupportTicketsByCustomerParams) ([]SupportTicket, error)
	ListSupportTicketsByPriority(ctx context.Context, arg ListSupportTicketsByPriorityParams) ([]SupportTicket, error)
	ListSupportTicketsByStaff(ctx context.Context, assignedStaffID pgtype.UUID) ([]SupportTicket, error)
	ListSupportTicketsByStatus(ctx context.Context, arg ListSupportTicketsByStatusParams) ([]SupportTicket, error)
	ListSystemRoles(ctx context.Context, shopID pgtype.UUID) ([]ShopRole, error)
	ListUnassignedTickets(ctx context.Context, shopID pgtype.UUID) ([]SupportTicket, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVariantsByProduct(ctx context.Context, arg ListVariantsByProductParams) ([]ProductVariant, error)
	ListWebhooks(ctx context.Context, shopID pgtype.UUID) ([]Webhook, error)
	ListWebhooksByTopic(ctx context.Context, arg ListWebhooksByTopicParams) ([]Webhook, error)
	MarkAllMessagesAsRead(ctx context.Context, arg MarkAllMessagesAsReadParams) error
	MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error
	MarkCartEmail1Sent(ctx context.Context, arg MarkCartEmail1SentParams) error
	MarkCartEmail2Sent(ctx context.Context, arg MarkCartEmail2SentParams) error
	MarkCartEmail3Sent(ctx context.Context, arg MarkCartEmail3SentParams) error
	MarkCartRecovered(ctx context.Context, arg MarkCartRecoveredParams) error
	MarkMessageAsRead(ctx context.Context, id uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MarkReorderRuleTriggered(ctx context.Context, id uuid.UUID) error
	PurgeOldSavedCarts(ctx context.Context, shopID uuid.UUID) error
	PurgeStaleSocialProofEvents(ctx context.Context, shopID uuid.UUID) error
	RecordLoyaltyTransaction(ctx context.Context, arg RecordLoyaltyTransactionParams) (LoyaltyTransaction, error)
	RecordReferralConversion(ctx context.Context, arg RecordReferralConversionParams) (ReferralConversion, error)
	RecordStockMovement(ctx context.Context, arg RecordStockMovementParams) (StockMovement, error)
	ReleaseReservedStock(ctx context.Context, arg ReleaseReservedStockParams) error
	RemoveFromWishlist(ctx context.Context, arg RemoveFromWishlistParams) error
	ReserveStock(ctx context.Context, arg ReserveStockParams) error
	ResolveSupportTicket(ctx context.Context, arg ResolveSupportTicketParams) (SupportTicket, error)
	RestoreCustomer(ctx context.Context, arg RestoreCustomerParams) (Customer, error)
	RestoreProduct(ctx context.Context, arg RestoreProductParams) (Product, error)
	SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error)
	// Full-text trigram search. Results ordered by similarity descending.
	// AI seam: this query will be replaced by a pgvector cosine similarity search
	//          once product embeddings are generated by the AI Engine.
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	SearchProductsFTS(ctx context.Context, arg SearchProductsFTSParams) ([]SearchProductsFTSRow, error)
	SetAddressAsDefault(ctx context.Context, arg SetAddressAsDefaultParams) error
	SetPrimaryImage(ctx context.Context, arg SetPrimaryImageParams) error
	SetProductLowStockThreshold(ctx context.Context, arg SetProductLowStockThresholdParams) (Product, error)
	SetProductStock(ctx context.Context, arg SetProductStockParams) (Product, error)
	SetRecoveryToken(ctx context.Context, arg SetRecoveryTokenParams) error
	SetReturnRefunded(ctx context.Context, arg SetReturnRefundedParams) (OrderReturn, error)
	SoftDeleteCustomer(ctx context.Context, arg SoftDeleteCustomerParams) error
	SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error
	SyncProductRatingCache(ctx context.Context, arg SyncProductRatingCacheParams) error
	ToggleCoupon(ctx context.Context, arg ToggleCouponParams) (Coupon, error)
	TogglePaymentMethod(ctx context.Context, arg TogglePaymentMethodParams) (ShopPaymentMethod, error)
	ToggleSupportAutomationRule(ctx context.Context, arg ToggleSupportAutomationRuleParams) (SupportAutomationRule, error)
	ToggleWebhook(ctx context.Context, arg ToggleWebhookParams) (Webhook, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategorySEO(ctx context.Context, arg UpdateCategorySEOParams) error
	UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerAddress(ctx context.Context, arg UpdateCustomerAddressParams) (CustomerAddress, error)
	UpdateCustomerPassword(ctx context.Context, arg UpdateCustomerPasswordParams) error
	UpdateImage(ctx context.Context, arg UpdateImageParams) (ProductImage, error)
	UpdateKBArticle(ctx context.Context, arg UpdateKBArticleParams) (KbArticle, error)
	UpdateLoyaltyTier(ctx context.Context, arg UpdateLoyaltyTierParams) (LoyaltyTier, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error)
	UpdatePlatformAdmin(ctx context.Context, arg UpdatePlatformAdminParams) (PlatformAdmin, error)
	UpdatePlatformAdminPassword(ctx context.Context, arg UpdatePlatformAdminPasswordParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductSEO(ctx context.Context, arg UpdateProductSEOParams) error
	UpdateProductSEOFields(ctx context.Context, arg UpdateProductSEOFieldsParams) error
	// ── SEO Scoring ───────────────────────────────────────────────────────────────
	UpdateProductSEOScore(ctx context.Context, arg UpdateProductSEOScoreParams) error
	UpdateProductStructuredData(ctx context.Context, arg UpdateProductStructuredDataParams) error
	UpdateReturnStatus(ctx context.Context, arg UpdateReturnStatusParams) (OrderReturn, error)
	UpdateReviewStatus(ctx context.Context, arg UpdateReviewStatusParams) (ProductReview, error)
	UpdateShippingRate(ctx context.Context, arg UpdateShippingRateParams) (ShippingRate, error)
	UpdateShippingZone(ctx context.Context, arg UpdateShippingZoneParams) (ShippingZone, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
	UpdateShopBilling(ctx context.Context, arg UpdateShopBillingParams) error
	UpdateShopInvoiceStatus(ctx context.Context, arg UpdateShopInvoiceStatusParams) (ShopInvoice, error)
	UpdateShopLocale(ctx context.Context, arg UpdateShopLocaleParams) (UpdateShopLocaleRow, error)
	UpdateShopNotificationPrefs(ctx context.Context, arg UpdateShopNotificationPrefsParams) error
	UpdateShopPaymentMethod(ctx context.Context, arg UpdateShopPaymentMethodParams) (ShopPaymentMethod, error)
	UpdateShopRole(ctx context.Context, arg UpdateShopRoleParams) (ShopRole, error)
	UpdateShopSEO(ctx context.Context, arg UpdateShopSEOParams) error
	UpdateShopStaffRole(ctx context.Context, arg UpdateShopStaffRoleParams) (ShopStaff, error)
	UpdateShopStatus(ctx context.Context, arg UpdateShopStatusParams) error
	UpdateSubscriptionBilling(ctx context.Context, arg UpdateSubscriptionBillingParams) (Subscription, error)
	UpdateSubscriptionOrderStatus(ctx context.Context, arg UpdateSubscriptionOrderStatusParams) (SubscriptionOrder, error)
	UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (SubscriptionPlan, error)
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error)
	UpdateSupportAutomationRule(ctx context.Context, arg UpdateSupportAutomationRuleParams) (SupportAutomationRule, error)
	UpdateSupportTicket(ctx context.Context, arg UpdateSupportTicketParams) (SupportTicket, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserSecrets(ctx context.Context, arg UpdateUserSecretsParams) (UserSecret, error)
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error)
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
	UpsertAIConfig(ctx context.Context, arg UpsertAIConfigParams) (AiConfig, error)
	UpsertBundleComponent(ctx context.Context, arg UpsertBundleComponentParams) (ProductBundle, error)
	UpsertCustomerNotifPrefs(ctx context.Context, arg UpsertCustomerNotifPrefsParams) (CustomerNotificationPref, error)
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error
	UpsertLoyaltyAccount(ctx context.Context, arg UpsertLoyaltyAccountParams) (LoyaltyAccount, error)
	UpsertLoyaltyProgram(ctx context.Context, arg UpsertLoyaltyProgramParams) (LoyaltyProgram, error)
	UpsertProductAttribute(ctx context.Context, arg UpsertProductAttributeParams) (ProductAttribute, error)
	UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error
	UpsertReferralConfig(ctx context.Context, arg UpsertReferralConfigParams) (ReferralConfig, error)
	UpsertReorderRule(ctx context.Context, arg UpsertReorderRuleParams) (ReorderRule, error)
	// ==================== Saved / Abandoned Carts ====================
	UpsertSavedCart(ctx context.Context, arg UpsertSavedCartParams) (SavedCart, error)
	// Returns the coupon only when active, not expired, and under usage limit.
	ValidateCoupon(ctx context.Context, arg ValidateCouponParams) (Coupon, error)
	VerifyUserEmail(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
