// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referral_config.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getReferralConfig = `-- name: GetReferralConfig :one

SELECT shop_id, is_enabled, referrer_reward_type, referrer_reward_value, referee_reward_type, referee_reward_value, min_order_amount, max_referrals_per_customer, cookie_window_days, created_at, updated_at FROM referral_config WHERE shop_id = $1
`

// ==================== Referral Config ====================
func (q *Queries) GetReferralConfig(ctx context.Context, shopID uuid.UUID) (ReferralConfig, error) {
	row := q.db.QueryRow(ctx, getReferralConfig, shopID)
	var i ReferralConfig
	err := row.Scan(
		&i.ShopID,
		&i.IsEnabled,
		&i.ReferrerRewardType,
		&i.ReferrerRewardValue,
		&i.RefereeRewardType,
		&i.RefereeRewardValue,
		&i.MinOrderAmount,
		&i.MaxReferralsPerCustomer,
		&i.CookieWindowDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReferralConfig = `-- name: UpsertReferralConfig :one
INSERT INTO referral_config (
    shop_id, is_enabled, referrer_reward_type, referrer_reward_value,
    referee_reward_type, referee_reward_value, min_order_amount,
    max_referrals_per_customer, cookie_window_days, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
ON CONFLICT (shop_id) DO UPDATE SET
    is_enabled                 = EXCLUDED.is_enabled,
    referrer_reward_type       = EXCLUDED.referrer_reward_type,
    referrer_reward_value      = EXCLUDED.referrer_reward_value,
    referee_reward_type        = EXCLUDED.referee_reward_type,
    referee_reward_value       = EXCLUDED.referee_reward_value,
    min_order_amount           = EXCLUDED.min_order_amount,
    max_referrals_per_customer = EXCLUDED.max_referrals_per_customer,
    cookie_window_days         = EXCLUDED.cookie_window_days,
    updated_at                 = NOW()
RETURNING shop_id, is_enabled, referrer_reward_type, referrer_reward_value, referee_reward_type, referee_reward_value, min_order_amount, max_referrals_per_customer, cookie_window_days, created_at, updated_at
`

type UpsertReferralConfigParams struct {
	ShopID                  uuid.UUID      `json:"shop_id"`
	IsEnabled               bool           `json:"is_enabled"`
	ReferrerRewardType      string         `json:"referrer_reward_type"`
	ReferrerRewardValue     pgtype.Numeric `json:"referrer_reward_value"`
	RefereeRewardType       string         `json:"referee_reward_type"`
	RefereeRewardValue      pgtype.Numeric `json:"referee_reward_value"`
	MinOrderAmount          pgtype.Numeric `json:"min_order_amount"`
	MaxReferralsPerCustomer pgtype.Int4    `json:"max_referrals_per_customer"`
	CookieWindowDays        int32          `json:"cookie_window_days"`
}

func (q *Queries) UpsertReferralConfig(ctx context.Context, arg UpsertReferralConfigParams) (ReferralConfig, error) {
	row := q.db.QueryRow(ctx, upsertReferralConfig,
		arg.ShopID,
		arg.IsEnabled,
		arg.ReferrerRewardType,
		arg.ReferrerRewardValue,
		arg.RefereeRewardType,
		arg.RefereeRewardValue,
		arg.MinOrderAmount,
		arg.MaxReferralsPerCustomer,
		arg.CookieWindowDays,
	)
	var i ReferralConfig
	err := row.Scan(
		&i.ShopID,
		&i.IsEnabled,
		&i.ReferrerRewardType,
		&i.ReferrerRewardValue,
		&i.RefereeRewardType,
		&i.RefereeRewardValue,
		&i.MinOrderAmount,
		&i.MaxReferralsPerCustomer,
		&i.CookieWindowDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
