// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seo.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProductsForSEOAudit = `-- name: CountProductsForSEOAudit :one
SELECT COUNT(*) FROM products
WHERE shop_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
`

func (q *Queries) CountProductsForSEOAudit(ctx context.Context, shopID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsForSEOAudit, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRedirects = `-- name: CountRedirects :one
SELECT COUNT(*) FROM url_redirects
WHERE shop_id = $1
`

func (q *Queries) CountRedirects(ctx context.Context, shopID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRedirects, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRedirect = `-- name: CreateRedirect :one


INSERT INTO url_redirects (shop_id, from_path, to_path, status_code)
VALUES ($1, $2, $3, $4)
ON CONFLICT (shop_id, from_path) DO UPDATE
    SET to_path = EXCLUDED.to_path, status_code = EXCLUDED.status_code
RETURNING id, shop_id, from_path, to_path, status_code, hit_count, created_at
`

type CreateRedirectParams struct {
	ShopID     uuid.UUID `json:"shop_id"`
	FromPath   string    `json:"from_path"`
	ToPath     string    `json:"to_path"`
	StatusCode int16     `json:"status_code"`
}

// ==================== SEO ====================
// ── URL Redirects ─────────────────────────────────────────────────────────────
func (q *Queries) CreateRedirect(ctx context.Context, arg CreateRedirectParams) (UrlRedirect, error) {
	row := q.db.QueryRow(ctx, createRedirect,
		arg.ShopID,
		arg.FromPath,
		arg.ToPath,
		arg.StatusCode,
	)
	var i UrlRedirect
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.FromPath,
		&i.ToPath,
		&i.StatusCode,
		&i.HitCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRedirect = `-- name: DeleteRedirect :exec
DELETE FROM url_redirects
WHERE id = $1 AND shop_id = $2
`

type DeleteRedirectParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeleteRedirect(ctx context.Context, arg DeleteRedirectParams) error {
	_, err := q.db.Exec(ctx, deleteRedirect, arg.ID, arg.ShopID)
	return err
}

const getAllProductsForSEOAudit = `-- name: GetAllProductsForSEOAudit :many
SELECT id, title, slug, seo_title, seo_description, description,
       review_count, price, seo_score, category_id
FROM products
WHERE shop_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
`

type GetAllProductsForSEOAuditRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	Slug           string         `json:"slug"`
	SeoTitle       pgtype.Text    `json:"seo_title"`
	SeoDescription pgtype.Text    `json:"seo_description"`
	Description    pgtype.Text    `json:"description"`
	ReviewCount    int32          `json:"review_count"`
	Price          pgtype.Numeric `json:"price"`
	SeoScore       int16          `json:"seo_score"`
	CategoryID     pgtype.UUID    `json:"category_id"`
}

func (q *Queries) GetAllProductsForSEOAudit(ctx context.Context, shopID pgtype.UUID) ([]GetAllProductsForSEOAuditRow, error) {
	rows, err := q.db.Query(ctx, getAllProductsForSEOAudit, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsForSEOAuditRow
	for rows.Next() {
		var i GetAllProductsForSEOAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.Description,
			&i.ReviewCount,
			&i.Price,
			&i.SeoScore,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesForSitemap = `-- name: GetCategoriesForSitemap :many
SELECT id, slug FROM categories
WHERE shop_id = $1
ORDER BY slug
`

type GetCategoriesForSitemapRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

func (q *Queries) GetCategoriesForSitemap(ctx context.Context, shopID pgtype.UUID) ([]GetCategoriesForSitemapRow, error) {
	rows, err := q.db.Query(ctx, getCategoriesForSitemap, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesForSitemapRow
	for rows.Next() {
		var i GetCategoriesForSitemapRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsForSEOAudit = `-- name: GetProductsForSEOAudit :many
SELECT id, title, slug, seo_title, seo_description, description,
       review_count, price, seo_score, category_id
FROM products
WHERE shop_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
ORDER BY seo_score ASC
LIMIT $2 OFFSET $3
`

type GetProductsForSEOAuditParams struct {
	ShopID pgtype.UUID `json:"shop_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetProductsForSEOAuditRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	Slug           string         `json:"slug"`
	SeoTitle       pgtype.Text    `json:"seo_title"`
	SeoDescription pgtype.Text    `json:"seo_description"`
	Description    pgtype.Text    `json:"description"`
	ReviewCount    int32          `json:"review_count"`
	Price          pgtype.Numeric `json:"price"`
	SeoScore       int16          `json:"seo_score"`
	CategoryID     pgtype.UUID    `json:"category_id"`
}

func (q *Queries) GetProductsForSEOAudit(ctx context.Context, arg GetProductsForSEOAuditParams) ([]GetProductsForSEOAuditRow, error) {
	rows, err := q.db.Query(ctx, getProductsForSEOAudit, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsForSEOAuditRow
	for rows.Next() {
		var i GetProductsForSEOAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.Description,
			&i.ReviewCount,
			&i.Price,
			&i.SeoScore,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsForSitemap = `-- name: GetProductsForSitemap :many

SELECT id, slug, created_at, avg_rating, review_count
FROM products
WHERE shop_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetProductsForSitemapRow struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AvgRating   pgtype.Numeric     `json:"avg_rating"`
	ReviewCount int32              `json:"review_count"`
}

// ── Sitemap ───────────────────────────────────────────────────────────────────
func (q *Queries) GetProductsForSitemap(ctx context.Context, shopID pgtype.UUID) ([]GetProductsForSitemapRow, error) {
	rows, err := q.db.Query(ctx, getProductsForSitemap, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsForSitemapRow
	for rows.Next() {
		var i GetProductsForSitemapRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CreatedAt,
			&i.AvgRating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedirect = `-- name: GetRedirect :one
SELECT id, shop_id, from_path, to_path, status_code, hit_count, created_at FROM url_redirects
WHERE shop_id = $1 AND from_path = $2
`

type GetRedirectParams struct {
	ShopID   uuid.UUID `json:"shop_id"`
	FromPath string    `json:"from_path"`
}

func (q *Queries) GetRedirect(ctx context.Context, arg GetRedirectParams) (UrlRedirect, error) {
	row := q.db.QueryRow(ctx, getRedirect, arg.ShopID, arg.FromPath)
	var i UrlRedirect
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.FromPath,
		&i.ToPath,
		&i.StatusCode,
		&i.HitCount,
		&i.CreatedAt,
	)
	return i, err
}

const incrementRedirectHitCount = `-- name: IncrementRedirectHitCount :exec
UPDATE url_redirects
SET hit_count = hit_count + 1
WHERE shop_id = $1 AND from_path = $2
`

type IncrementRedirectHitCountParams struct {
	ShopID   uuid.UUID `json:"shop_id"`
	FromPath string    `json:"from_path"`
}

func (q *Queries) IncrementRedirectHitCount(ctx context.Context, arg IncrementRedirectHitCountParams) error {
	_, err := q.db.Exec(ctx, incrementRedirectHitCount, arg.ShopID, arg.FromPath)
	return err
}

const listRedirects = `-- name: ListRedirects :many
SELECT id, shop_id, from_path, to_path, status_code, hit_count, created_at FROM url_redirects
WHERE shop_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRedirectsParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListRedirects(ctx context.Context, arg ListRedirectsParams) ([]UrlRedirect, error) {
	rows, err := q.db.Query(ctx, listRedirects, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UrlRedirect
	for rows.Next() {
		var i UrlRedirect
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.FromPath,
			&i.ToPath,
			&i.StatusCode,
			&i.HitCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductSEOFields = `-- name: UpdateProductSEOFields :exec
UPDATE products
SET seo_title = $3, seo_description = $4
WHERE id = $1 AND shop_id = $2
`

type UpdateProductSEOFieldsParams struct {
	ID             uuid.UUID   `json:"id"`
	ShopID         pgtype.UUID `json:"shop_id"`
	SeoTitle       pgtype.Text `json:"seo_title"`
	SeoDescription pgtype.Text `json:"seo_description"`
}

func (q *Queries) UpdateProductSEOFields(ctx context.Context, arg UpdateProductSEOFieldsParams) error {
	_, err := q.db.Exec(ctx, updateProductSEOFields,
		arg.ID,
		arg.ShopID,
		arg.SeoTitle,
		arg.SeoDescription,
	)
	return err
}

const updateProductSEOScore = `-- name: UpdateProductSEOScore :exec

UPDATE products
SET seo_score = $3
WHERE id = $1 AND shop_id = $2
`

type UpdateProductSEOScoreParams struct {
	ID       uuid.UUID   `json:"id"`
	ShopID   pgtype.UUID `json:"shop_id"`
	SeoScore int16       `json:"seo_score"`
}

// ── SEO Scoring ───────────────────────────────────────────────────────────────
func (q *Queries) UpdateProductSEOScore(ctx context.Context, arg UpdateProductSEOScoreParams) error {
	_, err := q.db.Exec(ctx, updateProductSEOScore, arg.ID, arg.ShopID, arg.SeoScore)
	return err
}

const updateProductStructuredData = `-- name: UpdateProductStructuredData :exec
UPDATE products
SET structured_data = $3
WHERE id = $1 AND shop_id = $2
`

type UpdateProductStructuredDataParams struct {
	ID             uuid.UUID   `json:"id"`
	ShopID         pgtype.UUID `json:"shop_id"`
	StructuredData []byte      `json:"structured_data"`
}

func (q *Queries) UpdateProductStructuredData(ctx context.Context, arg UpdateProductStructuredDataParams) error {
	_, err := q.db.Exec(ctx, updateProductStructuredData, arg.ID, arg.ShopID, arg.StructuredData)
	return err
}
