// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shop_payment_methods.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShopPaymentMethod = `-- name: CreateShopPaymentMethod :one

INSERT INTO shop_payment_methods (
    shop_id, provider, is_enabled, encrypted_credentials
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, shop_id, provider, is_enabled, encrypted_credentials
`

type CreateShopPaymentMethodParams struct {
	ShopID               pgtype.UUID     `json:"shop_id"`
	Provider             PaymentProvider `json:"provider"`
	IsEnabled            pgtype.Bool     `json:"is_enabled"`
	EncryptedCredentials string          `json:"encrypted_credentials"`
}

// ==================== Shop Payment Methods ====================
func (q *Queries) CreateShopPaymentMethod(ctx context.Context, arg CreateShopPaymentMethodParams) (ShopPaymentMethod, error) {
	row := q.db.QueryRow(ctx, createShopPaymentMethod,
		arg.ShopID,
		arg.Provider,
		arg.IsEnabled,
		arg.EncryptedCredentials,
	)
	var i ShopPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Provider,
		&i.IsEnabled,
		&i.EncryptedCredentials,
	)
	return i, err
}

const deleteShopPaymentMethod = `-- name: DeleteShopPaymentMethod :exec
DELETE FROM shop_payment_methods WHERE id = $1 AND shop_id = $2
`

type DeleteShopPaymentMethodParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) DeleteShopPaymentMethod(ctx context.Context, arg DeleteShopPaymentMethodParams) error {
	_, err := q.db.Exec(ctx, deleteShopPaymentMethod, arg.ID, arg.ShopID)
	return err
}

const getShopPaymentMethod = `-- name: GetShopPaymentMethod :one
SELECT id, shop_id, provider, is_enabled, encrypted_credentials FROM shop_payment_methods
WHERE id = $1 AND shop_id = $2
`

type GetShopPaymentMethodParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) GetShopPaymentMethod(ctx context.Context, arg GetShopPaymentMethodParams) (ShopPaymentMethod, error) {
	row := q.db.QueryRow(ctx, getShopPaymentMethod, arg.ID, arg.ShopID)
	var i ShopPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Provider,
		&i.IsEnabled,
		&i.EncryptedCredentials,
	)
	return i, err
}

const getShopPaymentMethodByProvider = `-- name: GetShopPaymentMethodByProvider :one
SELECT id, shop_id, provider, is_enabled, encrypted_credentials FROM shop_payment_methods
WHERE shop_id = $1 AND provider = $2
`

type GetShopPaymentMethodByProviderParams struct {
	ShopID   pgtype.UUID     `json:"shop_id"`
	Provider PaymentProvider `json:"provider"`
}

func (q *Queries) GetShopPaymentMethodByProvider(ctx context.Context, arg GetShopPaymentMethodByProviderParams) (ShopPaymentMethod, error) {
	row := q.db.QueryRow(ctx, getShopPaymentMethodByProvider, arg.ShopID, arg.Provider)
	var i ShopPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Provider,
		&i.IsEnabled,
		&i.EncryptedCredentials,
	)
	return i, err
}

const listEnabledPaymentMethods = `-- name: ListEnabledPaymentMethods :many
SELECT id, shop_id, provider, is_enabled, encrypted_credentials FROM shop_payment_methods
WHERE shop_id = $1 AND is_enabled = TRUE
ORDER BY provider ASC
`

func (q *Queries) ListEnabledPaymentMethods(ctx context.Context, shopID pgtype.UUID) ([]ShopPaymentMethod, error) {
	rows, err := q.db.Query(ctx, listEnabledPaymentMethods, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopPaymentMethod
	for rows.Next() {
		var i ShopPaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Provider,
			&i.IsEnabled,
			&i.EncryptedCredentials,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopPaymentMethods = `-- name: ListShopPaymentMethods :many
SELECT id, shop_id, provider, is_enabled, encrypted_credentials FROM shop_payment_methods
WHERE shop_id = $1
ORDER BY provider ASC
`

func (q *Queries) ListShopPaymentMethods(ctx context.Context, shopID pgtype.UUID) ([]ShopPaymentMethod, error) {
	rows, err := q.db.Query(ctx, listShopPaymentMethods, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopPaymentMethod
	for rows.Next() {
		var i ShopPaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Provider,
			&i.IsEnabled,
			&i.EncryptedCredentials,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const togglePaymentMethod = `-- name: TogglePaymentMethod :one
UPDATE shop_payment_methods SET is_enabled = NOT is_enabled
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, provider, is_enabled, encrypted_credentials
`

type TogglePaymentMethodParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) TogglePaymentMethod(ctx context.Context, arg TogglePaymentMethodParams) (ShopPaymentMethod, error) {
	row := q.db.QueryRow(ctx, togglePaymentMethod, arg.ID, arg.ShopID)
	var i ShopPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Provider,
		&i.IsEnabled,
		&i.EncryptedCredentials,
	)
	return i, err
}

const updateShopPaymentMethod = `-- name: UpdateShopPaymentMethod :one
UPDATE shop_payment_methods SET
    is_enabled = COALESCE($1, is_enabled),
    encrypted_credentials = COALESCE($2, encrypted_credentials)
WHERE id = $3 AND shop_id = $4
RETURNING id, shop_id, provider, is_enabled, encrypted_credentials
`

type UpdateShopPaymentMethodParams struct {
	IsEnabled            pgtype.Bool `json:"is_enabled"`
	EncryptedCredentials pgtype.Text `json:"encrypted_credentials"`
	ID                   uuid.UUID   `json:"id"`
	ShopID               pgtype.UUID `json:"shop_id"`
}

func (q *Queries) UpdateShopPaymentMethod(ctx context.Context, arg UpdateShopPaymentMethodParams) (ShopPaymentMethod, error) {
	row := q.db.QueryRow(ctx, updateShopPaymentMethod,
		arg.IsEnabled,
		arg.EncryptedCredentials,
		arg.ID,
		arg.ShopID,
	)
	var i ShopPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Provider,
		&i.IsEnabled,
		&i.EncryptedCredentials,
	)
	return i, err
}
