// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shop_roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShopRole = `-- name: CreateShopRole :one

INSERT INTO shop_roles (
    shop_id, parent_role_id, name, permissions, is_system_role
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, shop_id, parent_role_id, name, permissions, is_system_role
`

type CreateShopRoleParams struct {
	ShopID       pgtype.UUID `json:"shop_id"`
	ParentRoleID pgtype.UUID `json:"parent_role_id"`
	Name         string      `json:"name"`
	Permissions  []byte      `json:"permissions"`
	IsSystemRole pgtype.Bool `json:"is_system_role"`
}

// ==================== Shop Roles ====================
func (q *Queries) CreateShopRole(ctx context.Context, arg CreateShopRoleParams) (ShopRole, error) {
	row := q.db.QueryRow(ctx, createShopRole,
		arg.ShopID,
		arg.ParentRoleID,
		arg.Name,
		arg.Permissions,
		arg.IsSystemRole,
	)
	var i ShopRole
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentRoleID,
		&i.Name,
		&i.Permissions,
		&i.IsSystemRole,
	)
	return i, err
}

const deleteShopRole = `-- name: DeleteShopRole :exec
DELETE FROM shop_roles WHERE id = $1 AND is_system_role = FALSE
`

func (q *Queries) DeleteShopRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShopRole, id)
	return err
}

const getShopRole = `-- name: GetShopRole :one
SELECT id, shop_id, parent_role_id, name, permissions, is_system_role FROM shop_roles WHERE id = $1
`

func (q *Queries) GetShopRole(ctx context.Context, id uuid.UUID) (ShopRole, error) {
	row := q.db.QueryRow(ctx, getShopRole, id)
	var i ShopRole
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentRoleID,
		&i.Name,
		&i.Permissions,
		&i.IsSystemRole,
	)
	return i, err
}

const listShopRoles = `-- name: ListShopRoles :many
SELECT id, shop_id, parent_role_id, name, permissions, is_system_role FROM shop_roles
WHERE shop_id = $1
ORDER BY name ASC
`

func (q *Queries) ListShopRoles(ctx context.Context, shopID pgtype.UUID) ([]ShopRole, error) {
	rows, err := q.db.Query(ctx, listShopRoles, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopRole
	for rows.Next() {
		var i ShopRole
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ParentRoleID,
			&i.Name,
			&i.Permissions,
			&i.IsSystemRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemRoles = `-- name: ListSystemRoles :many
SELECT id, shop_id, parent_role_id, name, permissions, is_system_role FROM shop_roles
WHERE shop_id = $1 AND is_system_role = TRUE
ORDER BY name ASC
`

func (q *Queries) ListSystemRoles(ctx context.Context, shopID pgtype.UUID) ([]ShopRole, error) {
	rows, err := q.db.Query(ctx, listSystemRoles, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopRole
	for rows.Next() {
		var i ShopRole
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ParentRoleID,
			&i.Name,
			&i.Permissions,
			&i.IsSystemRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShopRole = `-- name: UpdateShopRole :one
UPDATE shop_roles SET
    name = COALESCE($1, name),
    permissions = COALESCE($2, permissions),
    parent_role_id = COALESCE($3, parent_role_id)
WHERE id = $4 AND is_system_role = FALSE
RETURNING id, shop_id, parent_role_id, name, permissions, is_system_role
`

type UpdateShopRoleParams struct {
	Name         pgtype.Text `json:"name"`
	Permissions  []byte      `json:"permissions"`
	ParentRoleID pgtype.UUID `json:"parent_role_id"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateShopRole(ctx context.Context, arg UpdateShopRoleParams) (ShopRole, error) {
	row := q.db.QueryRow(ctx, updateShopRole,
		arg.Name,
		arg.Permissions,
		arg.ParentRoleID,
		arg.ID,
	)
	var i ShopRole
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentRoleID,
		&i.Name,
		&i.Permissions,
		&i.IsSystemRole,
	)
	return i, err
}
