// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shop_staff.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countShopStaff = `-- name: CountShopStaff :one
SELECT COUNT(*) FROM shop_staff WHERE shop_id = $1
`

func (q *Queries) CountShopStaff(ctx context.Context, shopID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countShopStaff, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStaffByRole = `-- name: CountStaffByRole :one
SELECT COUNT(*) FROM shop_staff WHERE role_id = $1
`

func (q *Queries) CountStaffByRole(ctx context.Context, roleID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStaffByRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShopStaff = `-- name: CreateShopStaff :one

INSERT INTO shop_staff (
    shop_id, user_id, role_id, is_owner
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, shop_id, user_id, role_id, is_owner, joined_at
`

type CreateShopStaffParams struct {
	ShopID  pgtype.UUID `json:"shop_id"`
	UserID  pgtype.UUID `json:"user_id"`
	RoleID  pgtype.UUID `json:"role_id"`
	IsOwner pgtype.Bool `json:"is_owner"`
}

// ==================== Shop Staff ====================
func (q *Queries) CreateShopStaff(ctx context.Context, arg CreateShopStaffParams) (ShopStaff, error) {
	row := q.db.QueryRow(ctx, createShopStaff,
		arg.ShopID,
		arg.UserID,
		arg.RoleID,
		arg.IsOwner,
	)
	var i ShopStaff
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.RoleID,
		&i.IsOwner,
		&i.JoinedAt,
	)
	return i, err
}

const deleteShopStaff = `-- name: DeleteShopStaff :exec
DELETE FROM shop_staff WHERE id = $1
`

func (q *Queries) DeleteShopStaff(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShopStaff, id)
	return err
}

const deleteShopStaffProtected = `-- name: DeleteShopStaffProtected :exec
DELETE FROM shop_staff
WHERE id = $1 AND shop_id = $2 AND COALESCE(is_owner, false) = false
`

type DeleteShopStaffProtectedParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) DeleteShopStaffProtected(ctx context.Context, arg DeleteShopStaffProtectedParams) error {
	_, err := q.db.Exec(ctx, deleteShopStaffProtected, arg.ID, arg.ShopID)
	return err
}

const getShopOwner = `-- name: GetShopOwner :one
SELECT id, shop_id, user_id, role_id, is_owner, joined_at FROM shop_staff
WHERE shop_id = $1 AND is_owner = TRUE
`

func (q *Queries) GetShopOwner(ctx context.Context, shopID pgtype.UUID) (ShopStaff, error) {
	row := q.db.QueryRow(ctx, getShopOwner, shopID)
	var i ShopStaff
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.RoleID,
		&i.IsOwner,
		&i.JoinedAt,
	)
	return i, err
}

const getShopStaff = `-- name: GetShopStaff :one
SELECT id, shop_id, user_id, role_id, is_owner, joined_at FROM shop_staff WHERE id = $1
`

func (q *Queries) GetShopStaff(ctx context.Context, id uuid.UUID) (ShopStaff, error) {
	row := q.db.QueryRow(ctx, getShopStaff, id)
	var i ShopStaff
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.RoleID,
		&i.IsOwner,
		&i.JoinedAt,
	)
	return i, err
}

const getShopStaffByUserAndShop = `-- name: GetShopStaffByUserAndShop :one
SELECT id, shop_id, user_id, role_id, is_owner, joined_at FROM shop_staff
WHERE shop_id = $1 AND user_id = $2
`

type GetShopStaffByUserAndShopParams struct {
	ShopID pgtype.UUID `json:"shop_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetShopStaffByUserAndShop(ctx context.Context, arg GetShopStaffByUserAndShopParams) (ShopStaff, error) {
	row := q.db.QueryRow(ctx, getShopStaffByUserAndShop, arg.ShopID, arg.UserID)
	var i ShopStaff
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.RoleID,
		&i.IsOwner,
		&i.JoinedAt,
	)
	return i, err
}

const listShopStaff = `-- name: ListShopStaff :many
SELECT id, shop_id, user_id, role_id, is_owner, joined_at FROM shop_staff
WHERE shop_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListShopStaff(ctx context.Context, shopID pgtype.UUID) ([]ShopStaff, error) {
	rows, err := q.db.Query(ctx, listShopStaff, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopStaff
	for rows.Next() {
		var i ShopStaff
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.UserID,
			&i.RoleID,
			&i.IsOwner,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopsForUser = `-- name: ListShopsForUser :many
SELECT
    s.id         AS shop_id,
    s.name       AS shop_name,
    s.subdomain,
    sr.name      AS role_name,
    COALESCE(ss.is_owner, false) AS is_owner,
    ss.joined_at
FROM shop_staff ss
JOIN shops s  ON s.id  = ss.shop_id
LEFT JOIN shop_roles sr ON sr.id = ss.role_id
WHERE ss.user_id = $1
ORDER BY ss.joined_at ASC
`

type ListShopsForUserRow struct {
	ShopID    uuid.UUID          `json:"shop_id"`
	ShopName  string             `json:"shop_name"`
	Subdomain string             `json:"subdomain"`
	RoleName  pgtype.Text        `json:"role_name"`
	IsOwner   bool               `json:"is_owner"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListShopsForUser(ctx context.Context, userID pgtype.UUID) ([]ListShopsForUserRow, error) {
	rows, err := q.db.Query(ctx, listShopsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShopsForUserRow
	for rows.Next() {
		var i ListShopsForUserRow
		if err := rows.Scan(
			&i.ShopID,
			&i.ShopName,
			&i.Subdomain,
			&i.RoleName,
			&i.IsOwner,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffByUser = `-- name: ListStaffByUser :many
SELECT id, shop_id, user_id, role_id, is_owner, joined_at FROM shop_staff
WHERE user_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListStaffByUser(ctx context.Context, userID pgtype.UUID) ([]ShopStaff, error) {
	rows, err := q.db.Query(ctx, listStaffByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopStaff
	for rows.Next() {
		var i ShopStaff
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.UserID,
			&i.RoleID,
			&i.IsOwner,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffWithUsers = `-- name: ListStaffWithUsers :many
SELECT ss.id, ss.user_id, COALESCE(ss.is_owner, false) AS is_owner, ss.joined_at,
       u.email, u.full_name, u.phone
FROM shop_staff ss
JOIN users u ON u.id = ss.user_id
WHERE ss.shop_id = $1
ORDER BY ss.joined_at ASC
`

type ListStaffWithUsersRow struct {
	ID       uuid.UUID          `json:"id"`
	UserID   pgtype.UUID        `json:"user_id"`
	IsOwner  bool               `json:"is_owner"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
	Email    string             `json:"email"`
	FullName pgtype.Text        `json:"full_name"`
	Phone    pgtype.Text        `json:"phone"`
}

func (q *Queries) ListStaffWithUsers(ctx context.Context, shopID pgtype.UUID) ([]ListStaffWithUsersRow, error) {
	rows, err := q.db.Query(ctx, listStaffWithUsers, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffWithUsersRow
	for rows.Next() {
		var i ListStaffWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IsOwner,
			&i.JoinedAt,
			&i.Email,
			&i.FullName,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShopStaffRole = `-- name: UpdateShopStaffRole :one
UPDATE shop_staff SET role_id = $2
WHERE id = $1
RETURNING id, shop_id, user_id, role_id, is_owner, joined_at
`

type UpdateShopStaffRoleParams struct {
	ID     uuid.UUID   `json:"id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) UpdateShopStaffRole(ctx context.Context, arg UpdateShopStaffRoleParams) (ShopStaff, error) {
	row := q.db.QueryRow(ctx, updateShopStaffRole, arg.ID, arg.RoleID)
	var i ShopStaff
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.RoleID,
		&i.IsOwner,
		&i.JoinedAt,
	)
	return i, err
}
