// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (shop_id, customer_id, plan_id, status, current_period_start, current_period_end, next_billing_at, trial_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, shop_id, customer_id, plan_id, status, current_period_start, current_period_end, next_billing_at, trial_end, cancelled_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ShopID             uuid.UUID          `json:"shop_id"`
	CustomerID         uuid.UUID          `json:"customer_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextBillingAt      pgtype.Timestamptz `json:"next_billing_at"`
	TrialEnd           pgtype.Timestamptz `json:"trial_end"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ShopID,
		arg.CustomerID,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.NextBillingAt,
		arg.TrialEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextBillingAt,
		&i.TrialEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscriptionOrder = `-- name: CreateSubscriptionOrder :one
INSERT INTO subscription_orders (subscription_id, order_id, billing_date, status)
VALUES ($1, $2, $3, $4)
RETURNING id, subscription_id, order_id, billing_date, status, created_at
`

type CreateSubscriptionOrderParams struct {
	SubscriptionID uuid.UUID          `json:"subscription_id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	BillingDate    pgtype.Timestamptz `json:"billing_date"`
	Status         string             `json:"status"`
}

func (q *Queries) CreateSubscriptionOrder(ctx context.Context, arg CreateSubscriptionOrderParams) (SubscriptionOrder, error) {
	row := q.db.QueryRow(ctx, createSubscriptionOrder,
		arg.SubscriptionID,
		arg.OrderID,
		arg.BillingDate,
		arg.Status,
	)
	var i SubscriptionOrder
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.OrderID,
		&i.BillingDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscriptionPlan = `-- name: CreateSubscriptionPlan :one

INSERT INTO subscription_plans (shop_id, name, description, product_id, price, billing_cycle, trial_days, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, shop_id, name, description, product_id, price, billing_cycle, trial_days, is_active, created_at, updated_at
`

type CreateSubscriptionPlanParams struct {
	ShopID       uuid.UUID      `json:"shop_id"`
	Name         string         `json:"name"`
	Description  pgtype.Text    `json:"description"`
	ProductID    pgtype.UUID    `json:"product_id"`
	Price        pgtype.Numeric `json:"price"`
	BillingCycle string         `json:"billing_cycle"`
	TrialDays    int32          `json:"trial_days"`
	IsActive     bool           `json:"is_active"`
}

// sql/queries/subscriptions.sql
func (q *Queries) CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, createSubscriptionPlan,
		arg.ShopID,
		arg.Name,
		arg.Description,
		arg.ProductID,
		arg.Price,
		arg.BillingCycle,
		arg.TrialDays,
		arg.IsActive,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.ProductID,
		&i.Price,
		&i.BillingCycle,
		&i.TrialDays,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriptionPlan = `-- name: DeleteSubscriptionPlan :exec
UPDATE subscription_plans SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND shop_id = $2
`

type DeleteSubscriptionPlanParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeleteSubscriptionPlan(ctx context.Context, arg DeleteSubscriptionPlanParams) error {
	_, err := q.db.Exec(ctx, deleteSubscriptionPlan, arg.ID, arg.ShopID)
	return err
}

const getDueSubscriptions = `-- name: GetDueSubscriptions :many
SELECT s.id, s.shop_id, s.customer_id, s.plan_id, s.status, s.current_period_start, s.current_period_end, s.next_billing_at, s.trial_end, s.cancelled_at, s.created_at, s.updated_at, sp.price AS plan_price, sp.billing_cycle, sp.product_id AS plan_product_id
FROM subscriptions s
JOIN subscription_plans sp ON sp.id = s.plan_id
WHERE s.next_billing_at <= NOW()
  AND s.status IN ('active', 'trialing')
ORDER BY s.next_billing_at
LIMIT 100
`

type GetDueSubscriptionsRow struct {
	ID                 uuid.UUID          `json:"id"`
	ShopID             uuid.UUID          `json:"shop_id"`
	CustomerID         uuid.UUID          `json:"customer_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextBillingAt      pgtype.Timestamptz `json:"next_billing_at"`
	TrialEnd           pgtype.Timestamptz `json:"trial_end"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	PlanPrice          pgtype.Numeric     `json:"plan_price"`
	BillingCycle       string             `json:"billing_cycle"`
	PlanProductID      pgtype.UUID        `json:"plan_product_id"`
}

func (q *Queries) GetDueSubscriptions(ctx context.Context) ([]GetDueSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getDueSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueSubscriptionsRow
	for rows.Next() {
		var i GetDueSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CustomerID,
			&i.PlanID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextBillingAt,
			&i.TrialEnd,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanPrice,
			&i.BillingCycle,
			&i.PlanProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailedSubscriptionOrders = `-- name: GetFailedSubscriptionOrders :many
SELECT so.id, so.subscription_id, so.order_id, so.billing_date, so.status, so.created_at, s.customer_id, s.shop_id
FROM subscription_orders so
JOIN subscriptions s ON s.id = so.subscription_id
WHERE so.status = 'failed'
  AND so.billing_date > NOW() - INTERVAL '7 days'
ORDER BY so.billing_date DESC
`

type GetFailedSubscriptionOrdersRow struct {
	ID             uuid.UUID          `json:"id"`
	SubscriptionID uuid.UUID          `json:"subscription_id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	BillingDate    pgtype.Timestamptz `json:"billing_date"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CustomerID     uuid.UUID          `json:"customer_id"`
	ShopID         uuid.UUID          `json:"shop_id"`
}

func (q *Queries) GetFailedSubscriptionOrders(ctx context.Context) ([]GetFailedSubscriptionOrdersRow, error) {
	rows, err := q.db.Query(ctx, getFailedSubscriptionOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFailedSubscriptionOrdersRow
	for rows.Next() {
		var i GetFailedSubscriptionOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.OrderID,
			&i.BillingDate,
			&i.Status,
			&i.CreatedAt,
			&i.CustomerID,
			&i.ShopID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT s.id, s.shop_id, s.customer_id, s.plan_id, s.status, s.current_period_start, s.current_period_end, s.next_billing_at, s.trial_end, s.cancelled_at, s.created_at, s.updated_at, sp.name AS plan_name, sp.price AS plan_price, sp.billing_cycle
FROM subscriptions s
JOIN subscription_plans sp ON sp.id = s.plan_id
WHERE s.id = $1 AND s.shop_id = $2
`

type GetSubscriptionParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

type GetSubscriptionRow struct {
	ID                 uuid.UUID          `json:"id"`
	ShopID             uuid.UUID          `json:"shop_id"`
	CustomerID         uuid.UUID          `json:"customer_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextBillingAt      pgtype.Timestamptz `json:"next_billing_at"`
	TrialEnd           pgtype.Timestamptz `json:"trial_end"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	PlanName           string             `json:"plan_name"`
	PlanPrice          pgtype.Numeric     `json:"plan_price"`
	BillingCycle       string             `json:"billing_cycle"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (GetSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.ID, arg.ShopID)
	var i GetSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextBillingAt,
		&i.TrialEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanName,
		&i.PlanPrice,
		&i.BillingCycle,
	)
	return i, err
}

const getSubscriptionPlan = `-- name: GetSubscriptionPlan :one
SELECT id, shop_id, name, description, product_id, price, billing_cycle, trial_days, is_active, created_at, updated_at FROM subscription_plans
WHERE id = $1 AND shop_id = $2
`

type GetSubscriptionPlanParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) GetSubscriptionPlan(ctx context.Context, arg GetSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlan, arg.ID, arg.ShopID)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.ProductID,
		&i.Price,
		&i.BillingCycle,
		&i.TrialDays,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomerSubscriptions = `-- name: ListCustomerSubscriptions :many
SELECT s.id, s.shop_id, s.customer_id, s.plan_id, s.status, s.current_period_start, s.current_period_end, s.next_billing_at, s.trial_end, s.cancelled_at, s.created_at, s.updated_at, sp.name AS plan_name, sp.price AS plan_price, sp.billing_cycle
FROM subscriptions s
JOIN subscription_plans sp ON sp.id = s.plan_id
WHERE s.customer_id = $1 AND s.shop_id = $2
ORDER BY s.created_at DESC
`

type ListCustomerSubscriptionsParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	ShopID     uuid.UUID `json:"shop_id"`
}

type ListCustomerSubscriptionsRow struct {
	ID                 uuid.UUID          `json:"id"`
	ShopID             uuid.UUID          `json:"shop_id"`
	CustomerID         uuid.UUID          `json:"customer_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextBillingAt      pgtype.Timestamptz `json:"next_billing_at"`
	TrialEnd           pgtype.Timestamptz `json:"trial_end"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	PlanName           string             `json:"plan_name"`
	PlanPrice          pgtype.Numeric     `json:"plan_price"`
	BillingCycle       string             `json:"billing_cycle"`
}

func (q *Queries) ListCustomerSubscriptions(ctx context.Context, arg ListCustomerSubscriptionsParams) ([]ListCustomerSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerSubscriptions, arg.CustomerID, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerSubscriptionsRow
	for rows.Next() {
		var i ListCustomerSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CustomerID,
			&i.PlanID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextBillingAt,
			&i.TrialEnd,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanName,
			&i.PlanPrice,
			&i.BillingCycle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopSubscriptions = `-- name: ListShopSubscriptions :many
SELECT s.id, s.shop_id, s.customer_id, s.plan_id, s.status, s.current_period_start, s.current_period_end, s.next_billing_at, s.trial_end, s.cancelled_at, s.created_at, s.updated_at, sp.name AS plan_name, sp.price AS plan_price, sp.billing_cycle
FROM subscriptions s
JOIN subscription_plans sp ON sp.id = s.plan_id
WHERE s.shop_id = $1
ORDER BY s.created_at DESC
LIMIT $3 OFFSET $2
`

type ListShopSubscriptionsParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Off    int32     `json:"off"`
	Lim    int32     `json:"lim"`
}

type ListShopSubscriptionsRow struct {
	ID                 uuid.UUID          `json:"id"`
	ShopID             uuid.UUID          `json:"shop_id"`
	CustomerID         uuid.UUID          `json:"customer_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextBillingAt      pgtype.Timestamptz `json:"next_billing_at"`
	TrialEnd           pgtype.Timestamptz `json:"trial_end"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	PlanName           string             `json:"plan_name"`
	PlanPrice          pgtype.Numeric     `json:"plan_price"`
	BillingCycle       string             `json:"billing_cycle"`
}

func (q *Queries) ListShopSubscriptions(ctx context.Context, arg ListShopSubscriptionsParams) ([]ListShopSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listShopSubscriptions, arg.ShopID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShopSubscriptionsRow
	for rows.Next() {
		var i ListShopSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CustomerID,
			&i.PlanID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextBillingAt,
			&i.TrialEnd,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanName,
			&i.PlanPrice,
			&i.BillingCycle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionPlans = `-- name: ListSubscriptionPlans :many
SELECT id, shop_id, name, description, product_id, price, billing_cycle, trial_days, is_active, created_at, updated_at FROM subscription_plans
WHERE shop_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionPlans(ctx context.Context, shopID uuid.UUID) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listSubscriptionPlans, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionPlan
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Description,
			&i.ProductID,
			&i.Price,
			&i.BillingCycle,
			&i.TrialDays,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionBilling = `-- name: UpdateSubscriptionBilling :one
UPDATE subscriptions
SET next_billing_at = $1,
    current_period_start = $2,
    current_period_end = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $5
RETURNING id, shop_id, customer_id, plan_id, status, current_period_start, current_period_end, next_billing_at, trial_end, cancelled_at, created_at, updated_at
`

type UpdateSubscriptionBillingParams struct {
	NextBillingAt      pgtype.Timestamptz `json:"next_billing_at"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	Status             string             `json:"status"`
	ID                 uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateSubscriptionBilling(ctx context.Context, arg UpdateSubscriptionBillingParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionBilling,
		arg.NextBillingAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.Status,
		arg.ID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextBillingAt,
		&i.TrialEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionOrderStatus = `-- name: UpdateSubscriptionOrderStatus :one
UPDATE subscription_orders
SET status = $1
WHERE id = $2
RETURNING id, subscription_id, order_id, billing_date, status, created_at
`

type UpdateSubscriptionOrderStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSubscriptionOrderStatus(ctx context.Context, arg UpdateSubscriptionOrderStatusParams) (SubscriptionOrder, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionOrderStatus, arg.Status, arg.ID)
	var i SubscriptionOrder
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.OrderID,
		&i.BillingDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :one
UPDATE subscription_plans
SET name = $1, description = $2, price = $3,
    billing_cycle = $4, trial_days = $5, is_active = $6,
    updated_at = NOW()
WHERE id = $7 AND shop_id = $8
RETURNING id, shop_id, name, description, product_id, price, billing_cycle, trial_days, is_active, created_at, updated_at
`

type UpdateSubscriptionPlanParams struct {
	Name         string         `json:"name"`
	Description  pgtype.Text    `json:"description"`
	Price        pgtype.Numeric `json:"price"`
	BillingCycle string         `json:"billing_cycle"`
	TrialDays    int32          `json:"trial_days"`
	IsActive     bool           `json:"is_active"`
	ID           uuid.UUID      `json:"id"`
	ShopID       uuid.UUID      `json:"shop_id"`
}

func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionPlan,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.BillingCycle,
		arg.TrialDays,
		arg.IsActive,
		arg.ID,
		arg.ShopID,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.ProductID,
		&i.Price,
		&i.BillingCycle,
		&i.TrialDays,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :one
UPDATE subscriptions
SET status = $1, cancelled_at = $2, updated_at = NOW()
WHERE id = $3 AND shop_id = $4
RETURNING id, shop_id, customer_id, plan_id, status, current_period_start, current_period_end, next_billing_at, trial_end, cancelled_at, created_at, updated_at
`

type UpdateSubscriptionStatusParams struct {
	Status      string             `json:"status"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	ID          uuid.UUID          `json:"id"`
	ShopID      uuid.UUID          `json:"shop_id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStatus,
		arg.Status,
		arg.CancelledAt,
		arg.ID,
		arg.ShopID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextBillingAt,
		&i.TrialEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
