/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Envelope,
  ErrorResponse,
  GenericObject
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List all shipping rates; Tenant-scoped
 * @summary List all shipping rates
 */
export const getApiV1ShippingRates = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/shipping/rates`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1ShippingRatesQueryKey = () => {
    return [
    `/api/v1/shipping/rates`
    ] as const;
    }

    
export const getGetApiV1ShippingRatesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ShippingRatesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ShippingRates>>> = ({ signal }) => getApiV1ShippingRates(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ShippingRatesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ShippingRates>>>
export type GetApiV1ShippingRatesQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1ShippingRates<TData = Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShippingRates>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShippingRates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShippingRates<TData = Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShippingRates>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShippingRates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShippingRates<TData = Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all shipping rates
 */

export function useGetApiV1ShippingRates<TData = Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ShippingRatesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create shipping rate; Tenant-scoped
 * @summary Create shipping rate
 */
export const postApiV1ShippingRates = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/shipping/rates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1ShippingRatesMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ShippingRates>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ShippingRates>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1ShippingRates'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ShippingRates>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1ShippingRates(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ShippingRatesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ShippingRates>>>
    export type PostApiV1ShippingRatesMutationBody = GenericObject
    export type PostApiV1ShippingRatesMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Create shipping rate
 */
export const usePostApiV1ShippingRates = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ShippingRates>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ShippingRates>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1ShippingRatesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete shipping rate; Tenant-scoped
 * @summary Delete shipping rate
 */
export const deleteApiV1ShippingRatesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/shipping/rates/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1ShippingRatesIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ShippingRatesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ShippingRatesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1ShippingRatesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1ShippingRatesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1ShippingRatesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1ShippingRatesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1ShippingRatesId>>>
    
    export type DeleteApiV1ShippingRatesIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Delete shipping rate
 */
export const useDeleteApiV1ShippingRatesId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ShippingRatesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1ShippingRatesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1ShippingRatesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get shipping rate by ID; Tenant-scoped
 * @summary Get shipping rate by ID
 */
export const getApiV1ShippingRatesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/shipping/rates/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1ShippingRatesIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/shipping/rates/${id}`
    ] as const;
    }

    
export const getGetApiV1ShippingRatesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ShippingRatesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ShippingRatesId>>> = ({ signal }) => getApiV1ShippingRatesId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ShippingRatesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ShippingRatesId>>>
export type GetApiV1ShippingRatesIdQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1ShippingRatesId<TData = Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShippingRatesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShippingRatesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShippingRatesId<TData = Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShippingRatesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShippingRatesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShippingRatesId<TData = Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get shipping rate by ID
 */

export function useGetApiV1ShippingRatesId<TData = Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingRatesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ShippingRatesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update shipping rate; Tenant-scoped
 * @summary Update shipping rate
 */
export const patchApiV1ShippingRatesId = (
    id: string,
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/shipping/rates/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1ShippingRatesIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ShippingRatesId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ShippingRatesId>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1ShippingRatesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1ShippingRatesId>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1ShippingRatesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1ShippingRatesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1ShippingRatesId>>>
    export type PatchApiV1ShippingRatesIdMutationBody = GenericObject
    export type PatchApiV1ShippingRatesIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update shipping rate
 */
export const usePatchApiV1ShippingRatesId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ShippingRatesId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1ShippingRatesId>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1ShippingRatesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List shipping zones; Tenant-scoped
 * @summary List shipping zones
 */
export const getApiV1ShippingZones = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/shipping/zones`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1ShippingZonesQueryKey = () => {
    return [
    `/api/v1/shipping/zones`
    ] as const;
    }

    
export const getGetApiV1ShippingZonesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ShippingZonesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ShippingZones>>> = ({ signal }) => getApiV1ShippingZones(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ShippingZonesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ShippingZones>>>
export type GetApiV1ShippingZonesQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1ShippingZones<TData = Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShippingZones>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShippingZones>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShippingZones<TData = Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShippingZones>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShippingZones>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShippingZones<TData = Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List shipping zones
 */

export function useGetApiV1ShippingZones<TData = Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZones>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ShippingZonesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create shipping zone; Tenant-scoped
 * @summary Create shipping zone
 */
export const postApiV1ShippingZones = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/shipping/zones`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1ShippingZonesMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ShippingZones>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ShippingZones>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1ShippingZones'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ShippingZones>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1ShippingZones(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ShippingZonesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ShippingZones>>>
    export type PostApiV1ShippingZonesMutationBody = GenericObject
    export type PostApiV1ShippingZonesMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Create shipping zone
 */
export const usePostApiV1ShippingZones = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ShippingZones>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ShippingZones>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1ShippingZonesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete shipping zone; Tenant-scoped
 * @summary Delete shipping zone
 */
export const deleteApiV1ShippingZonesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/shipping/zones/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1ShippingZonesIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ShippingZonesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ShippingZonesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1ShippingZonesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1ShippingZonesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1ShippingZonesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1ShippingZonesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1ShippingZonesId>>>
    
    export type DeleteApiV1ShippingZonesIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Delete shipping zone
 */
export const useDeleteApiV1ShippingZonesId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ShippingZonesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1ShippingZonesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1ShippingZonesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get shipping zone by ID; Tenant-scoped
 * @summary Get shipping zone by ID
 */
export const getApiV1ShippingZonesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/shipping/zones/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1ShippingZonesIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/shipping/zones/${id}`
    ] as const;
    }

    
export const getGetApiV1ShippingZonesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ShippingZonesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ShippingZonesId>>> = ({ signal }) => getApiV1ShippingZonesId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ShippingZonesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ShippingZonesId>>>
export type GetApiV1ShippingZonesIdQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1ShippingZonesId<TData = Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShippingZonesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShippingZonesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShippingZonesId<TData = Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShippingZonesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShippingZonesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShippingZonesId<TData = Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get shipping zone by ID
 */

export function useGetApiV1ShippingZonesId<TData = Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ShippingZonesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update shipping zone; Tenant-scoped
 * @summary Update shipping zone
 */
export const patchApiV1ShippingZonesId = (
    id: string,
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/shipping/zones/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1ShippingZonesIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ShippingZonesId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ShippingZonesId>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1ShippingZonesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1ShippingZonesId>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1ShippingZonesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1ShippingZonesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1ShippingZonesId>>>
    export type PatchApiV1ShippingZonesIdMutationBody = GenericObject
    export type PatchApiV1ShippingZonesIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update shipping zone
 */
export const usePatchApiV1ShippingZonesId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ShippingZonesId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1ShippingZonesId>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1ShippingZonesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List shipping rates for zone; Tenant-scoped
 * @summary List shipping rates for zone
 */
export const getApiV1ShippingZonesIdRates = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/shipping/zones/${id}/rates`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1ShippingZonesIdRatesQueryKey = (id?: string,) => {
    return [
    `/api/v1/shipping/zones/${id}/rates`
    ] as const;
    }

    
export const getGetApiV1ShippingZonesIdRatesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ShippingZonesIdRatesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>> = ({ signal }) => getApiV1ShippingZonesIdRates(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ShippingZonesIdRatesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>>
export type GetApiV1ShippingZonesIdRatesQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1ShippingZonesIdRates<TData = Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShippingZonesIdRates<TData = Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShippingZonesIdRates<TData = Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List shipping rates for zone
 */

export function useGetApiV1ShippingZonesIdRates<TData = Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShippingZonesIdRates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ShippingZonesIdRatesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



