/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Envelope,
  ErrorResponse,
  GenericObject
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List webhooks; Tenant-scoped
 * @summary List webhooks
 */
export const getApiV1Webhooks = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/webhooks`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1WebhooksQueryKey = () => {
    return [
    `/api/v1/webhooks`
    ] as const;
    }

    
export const getGetApiV1WebhooksQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Webhooks>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Webhooks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1WebhooksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Webhooks>>> = ({ signal }) => getApiV1Webhooks(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Webhooks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1WebhooksQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Webhooks>>>
export type GetApiV1WebhooksQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1Webhooks<TData = Awaited<ReturnType<typeof getApiV1Webhooks>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Webhooks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Webhooks>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Webhooks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Webhooks<TData = Awaited<ReturnType<typeof getApiV1Webhooks>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Webhooks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Webhooks>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Webhooks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Webhooks<TData = Awaited<ReturnType<typeof getApiV1Webhooks>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Webhooks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List webhooks
 */

export function useGetApiV1Webhooks<TData = Awaited<ReturnType<typeof getApiV1Webhooks>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Webhooks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1WebhooksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create webhook; Tenant-scoped
 * @summary Create webhook
 */
export const postApiV1Webhooks = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/webhooks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1WebhooksMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Webhooks>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Webhooks>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1Webhooks'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Webhooks>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Webhooks(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1WebhooksMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Webhooks>>>
    export type PostApiV1WebhooksMutationBody = GenericObject
    export type PostApiV1WebhooksMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Create webhook
 */
export const usePostApiV1Webhooks = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Webhooks>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Webhooks>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1WebhooksMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete webhook; Tenant-scoped
 * @summary Delete webhook
 */
export const deleteApiV1WebhooksId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/webhooks/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1WebhooksIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1WebhooksId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1WebhooksId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1WebhooksId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1WebhooksId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1WebhooksId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1WebhooksIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1WebhooksId>>>
    
    export type DeleteApiV1WebhooksIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Delete webhook
 */
export const useDeleteApiV1WebhooksId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1WebhooksId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1WebhooksId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1WebhooksIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get webhook by ID; Tenant-scoped
 * @summary Get webhook by ID
 */
export const getApiV1WebhooksId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/webhooks/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1WebhooksIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/webhooks/${id}`
    ] as const;
    }

    
export const getGetApiV1WebhooksIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1WebhooksIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1WebhooksId>>> = ({ signal }) => getApiV1WebhooksId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1WebhooksIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1WebhooksId>>>
export type GetApiV1WebhooksIdQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1WebhooksId<TData = Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1WebhooksId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1WebhooksId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1WebhooksId<TData = Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1WebhooksId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1WebhooksId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1WebhooksId<TData = Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get webhook by ID
 */

export function useGetApiV1WebhooksId<TData = Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1WebhooksId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1WebhooksIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update webhook; Tenant-scoped
 * @summary Update webhook
 */
export const patchApiV1WebhooksId = (
    id: string,
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/webhooks/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1WebhooksIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1WebhooksId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1WebhooksId>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1WebhooksId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1WebhooksId>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1WebhooksId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1WebhooksIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1WebhooksId>>>
    export type PatchApiV1WebhooksIdMutationBody = GenericObject
    export type PatchApiV1WebhooksIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update webhook
 */
export const usePatchApiV1WebhooksId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1WebhooksId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1WebhooksId>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1WebhooksIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Toggle webhook active/inactive; Tenant-scoped
 * @summary Toggle webhook active/inactive
 */
export const postApiV1WebhooksIdToggle = (
    id: string,
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/webhooks/${id}/toggle`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1WebhooksIdToggleMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1WebhooksIdToggle>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1WebhooksIdToggle>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1WebhooksIdToggle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1WebhooksIdToggle>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1WebhooksIdToggle(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1WebhooksIdToggleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1WebhooksIdToggle>>>
    export type PostApiV1WebhooksIdToggleMutationBody = GenericObject
    export type PostApiV1WebhooksIdToggleMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Toggle webhook active/inactive
 */
export const usePostApiV1WebhooksIdToggle = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1WebhooksIdToggle>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1WebhooksIdToggle>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1WebhooksIdToggleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    