/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Envelope,
  ErrorResponse,
  GenericObject
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List KB articles; Public
 * @summary List KB articles
 */
export const getApiV1SupportArticles = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/articles`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1SupportArticlesQueryKey = () => {
    return [
    `/api/v1/support/articles`
    ] as const;
    }

    
export const getGetApiV1SupportArticlesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError = ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SupportArticlesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SupportArticles>>> = ({ signal }) => getApiV1SupportArticles(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SupportArticlesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SupportArticles>>>
export type GetApiV1SupportArticlesQueryError = ErrorResponse | ErrorResponse


export function useGetApiV1SupportArticles<TData = Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError = ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SupportArticles>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SupportArticles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SupportArticles<TData = Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SupportArticles>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SupportArticles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SupportArticles<TData = Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List KB articles
 */

export function useGetApiV1SupportArticles<TData = Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SupportArticlesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create KB article; Tenant-scoped
 * @summary Create KB article
 */
export const postApiV1SupportArticles = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/articles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SupportArticlesMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportArticles>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportArticles>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1SupportArticles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SupportArticles>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SupportArticles(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SupportArticlesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SupportArticles>>>
    export type PostApiV1SupportArticlesMutationBody = GenericObject
    export type PostApiV1SupportArticlesMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Create KB article
 */
export const usePostApiV1SupportArticles = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportArticles>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SupportArticles>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SupportArticlesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get KB article by slug; Public
 * @summary Get KB article by slug
 */
export const getApiV1SupportArticlesSlug = (
    articleRef: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/articles/${articleRef}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1SupportArticlesSlugQueryKey = (articleRef?: string,) => {
    return [
    `/api/v1/support/articles/${articleRef}`
    ] as const;
    }

    
export const getGetApiV1SupportArticlesSlugQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError = ErrorResponse | ErrorResponse | ErrorResponse>(articleRef: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SupportArticlesSlugQueryKey(articleRef);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>> = ({ signal }) => getApiV1SupportArticlesSlug(articleRef, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(articleRef), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SupportArticlesSlugQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>>
export type GetApiV1SupportArticlesSlugQueryError = ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1SupportArticlesSlug<TData = Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError = ErrorResponse | ErrorResponse | ErrorResponse>(
 articleRef: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SupportArticlesSlug<TData = Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError = ErrorResponse | ErrorResponse | ErrorResponse>(
 articleRef: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SupportArticlesSlug<TData = Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError = ErrorResponse | ErrorResponse | ErrorResponse>(
 articleRef: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get KB article by slug
 */

export function useGetApiV1SupportArticlesSlug<TData = Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError = ErrorResponse | ErrorResponse | ErrorResponse>(
 articleRef: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportArticlesSlug>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SupportArticlesSlugQueryOptions(articleRef,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Delete KB article; Tenant-scoped
 * @summary Delete KB article
 */
export const deleteApiV1SupportArticlesId = (
    articleRef: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/support/articles/${articleRef}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1SupportArticlesIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SupportArticlesId>>, TError,{articleRef: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SupportArticlesId>>, TError,{articleRef: string}, TContext> => {

const mutationKey = ['deleteApiV1SupportArticlesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1SupportArticlesId>>, {articleRef: string}> = (props) => {
          const {articleRef} = props ?? {};

          return  deleteApiV1SupportArticlesId(articleRef,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1SupportArticlesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1SupportArticlesId>>>
    
    export type DeleteApiV1SupportArticlesIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Delete KB article
 */
export const useDeleteApiV1SupportArticlesId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SupportArticlesId>>, TError,{articleRef: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1SupportArticlesId>>,
        TError,
        {articleRef: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1SupportArticlesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Update KB article; Tenant-scoped
 * @summary Update KB article
 */
export const patchApiV1SupportArticlesId = (
    articleRef: string,
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/articles/${articleRef}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1SupportArticlesIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SupportArticlesId>>, TError,{articleRef: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SupportArticlesId>>, TError,{articleRef: string;data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1SupportArticlesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1SupportArticlesId>>, {articleRef: string;data: GenericObject}> = (props) => {
          const {articleRef,data} = props ?? {};

          return  patchApiV1SupportArticlesId(articleRef,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1SupportArticlesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1SupportArticlesId>>>
    export type PatchApiV1SupportArticlesIdMutationBody = GenericObject
    export type PatchApiV1SupportArticlesIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update KB article
 */
export const usePatchApiV1SupportArticlesId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SupportArticlesId>>, TError,{articleRef: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1SupportArticlesId>>,
        TError,
        {articleRef: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1SupportArticlesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Mark KB article as helpful; Tenant-scoped
 * @summary Mark KB article as helpful
 */
export const postApiV1SupportArticlesIdHelpful = (
    id: string,
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/articles/${id}/helpful`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SupportArticlesIdHelpfulMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportArticlesIdHelpful>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportArticlesIdHelpful>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1SupportArticlesIdHelpful'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SupportArticlesIdHelpful>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SupportArticlesIdHelpful(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SupportArticlesIdHelpfulMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SupportArticlesIdHelpful>>>
    export type PostApiV1SupportArticlesIdHelpfulMutationBody = GenericObject
    export type PostApiV1SupportArticlesIdHelpfulMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Mark KB article as helpful
 */
export const usePostApiV1SupportArticlesIdHelpful = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportArticlesIdHelpful>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SupportArticlesIdHelpful>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SupportArticlesIdHelpfulMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List tickets; Split between customer (own) and staff (all); Tenant-scoped List all tickets (staff view); Tenant-scoped
 * @summary List tickets
 */
export const getApiV1SupportTickets = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/tickets`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1SupportTicketsQueryKey = () => {
    return [
    `/api/v1/support/tickets`
    ] as const;
    }

    
export const getGetApiV1SupportTicketsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SupportTicketsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SupportTickets>>> = ({ signal }) => getApiV1SupportTickets(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SupportTicketsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SupportTickets>>>
export type GetApiV1SupportTicketsQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1SupportTickets<TData = Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SupportTickets>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SupportTickets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SupportTickets<TData = Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SupportTickets>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SupportTickets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SupportTickets<TData = Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List tickets
 */

export function useGetApiV1SupportTickets<TData = Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTickets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SupportTicketsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create support ticket; Tenant-scoped
 * @summary Create support ticket
 */
export const postApiV1SupportTickets = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/tickets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SupportTicketsMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportTickets>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportTickets>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1SupportTickets'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SupportTickets>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SupportTickets(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SupportTicketsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SupportTickets>>>
    export type PostApiV1SupportTicketsMutationBody = GenericObject
    export type PostApiV1SupportTicketsMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Create support ticket
 */
export const usePostApiV1SupportTickets = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportTickets>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SupportTickets>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SupportTicketsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get ticket; Split between customer (ownership verified) and staff; Tenant-scoped Get ticket with all details (staff view); Tenant-scoped
 * @summary Get ticket
 */
export const getApiV1SupportTicketsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/tickets/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1SupportTicketsIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/support/tickets/${id}`
    ] as const;
    }

    
export const getGetApiV1SupportTicketsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SupportTicketsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SupportTicketsId>>> = ({ signal }) => getApiV1SupportTicketsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SupportTicketsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SupportTicketsId>>>
export type GetApiV1SupportTicketsIdQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1SupportTicketsId<TData = Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SupportTicketsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SupportTicketsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SupportTicketsId<TData = Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SupportTicketsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SupportTicketsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SupportTicketsId<TData = Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get ticket
 */

export function useGetApiV1SupportTicketsId<TData = Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SupportTicketsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SupportTicketsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update ticket status/priority; Tenant-scoped
 * @summary Update ticket status/priority
 */
export const patchApiV1SupportTicketsId = (
    id: string,
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/tickets/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1SupportTicketsIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SupportTicketsId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SupportTicketsId>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1SupportTicketsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1SupportTicketsId>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1SupportTicketsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1SupportTicketsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1SupportTicketsId>>>
    export type PatchApiV1SupportTicketsIdMutationBody = GenericObject
    export type PatchApiV1SupportTicketsIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update ticket status/priority
 */
export const usePatchApiV1SupportTicketsId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SupportTicketsId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1SupportTicketsId>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1SupportTicketsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Assign ticket to staff member; Tenant-scoped
 * @summary Assign ticket to staff member
 */
export const patchApiV1SupportTicketsIdAssign = (
    id: string,
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/tickets/${id}/assign`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1SupportTicketsIdAssignMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SupportTicketsIdAssign>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SupportTicketsIdAssign>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1SupportTicketsIdAssign'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1SupportTicketsIdAssign>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1SupportTicketsIdAssign(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1SupportTicketsIdAssignMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1SupportTicketsIdAssign>>>
    export type PatchApiV1SupportTicketsIdAssignMutationBody = GenericObject
    export type PatchApiV1SupportTicketsIdAssignMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Assign ticket to staff member
 */
export const usePatchApiV1SupportTicketsIdAssign = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1SupportTicketsIdAssign>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1SupportTicketsIdAssign>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1SupportTicketsIdAssignMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Add ticket message; Split between customer and staff; Tenant-scoped
 * @summary Add ticket message
 */
export const postApiV1SupportTicketsIdMessages = (
    id: string,
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/tickets/${id}/messages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SupportTicketsIdMessagesMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportTicketsIdMessages>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportTicketsIdMessages>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1SupportTicketsIdMessages'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SupportTicketsIdMessages>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SupportTicketsIdMessages(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SupportTicketsIdMessagesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SupportTicketsIdMessages>>>
    export type PostApiV1SupportTicketsIdMessagesMutationBody = GenericObject
    export type PostApiV1SupportTicketsIdMessagesMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Add ticket message
 */
export const usePostApiV1SupportTicketsIdMessages = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportTicketsIdMessages>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SupportTicketsIdMessages>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SupportTicketsIdMessagesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Create guest support ticket; No auth required
 * @summary Create guest support ticket
 */
export const postApiV1SupportTicketsGuest = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/support/tickets/guest`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1SupportTicketsGuestMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportTicketsGuest>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportTicketsGuest>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1SupportTicketsGuest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SupportTicketsGuest>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SupportTicketsGuest(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SupportTicketsGuestMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SupportTicketsGuest>>>
    export type PostApiV1SupportTicketsGuestMutationBody = GenericObject
    export type PostApiV1SupportTicketsGuestMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Create guest support ticket
 */
export const usePostApiV1SupportTicketsGuest = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SupportTicketsGuest>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SupportTicketsGuest>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1SupportTicketsGuestMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    