/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddStaffRequest,
  AdminLoginRequest,
  AdminMeResponseEnvelope,
  AuthResponseEnvelope,
  Challenge2FARequest,
  CustomerChangePasswordRequest,
  CustomerLoginRequest,
  CustomerMeResponseEnvelope,
  CustomerRegisterRequest,
  CustomerUpdateMeRequest,
  Envelope,
  ErrorResponse,
  ForgotPasswordRequest,
  GenericObject,
  LoginRequest,
  MeResponseEnvelope,
  MessageEnvelope,
  PostApiV1AuthStaffLogin200,
  RecoverAccountRequest,
  RefreshRequest,
  RegisterRequest,
  ResetPasswordRequest,
  SelectShopRequest,
  Setup2FAResponseEnvelope,
  ShopSettingsResponseEnvelope,
  StaffChangePasswordRequest,
  StaffMemberListEnvelope,
  StaffMemberResponseEnvelope,
  StaffUpdateProfileRequest,
  UpdateShopSettingsRequest,
  UserResponseEnvelope,
  Verify2FARequest
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Platform admin login; Rate-limited by IP
 * @summary Platform admin login
 */
export const postApiV1AuthAdminLogin = (
    adminLoginRequest: AdminLoginRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponseEnvelope>(
      {url: `/api/v1/auth/admin/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminLoginRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthAdminLoginMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthAdminLogin>>, TError,{data: AdminLoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthAdminLogin>>, TError,{data: AdminLoginRequest}, TContext> => {

const mutationKey = ['postApiV1AuthAdminLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthAdminLogin>>, {data: AdminLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthAdminLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthAdminLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthAdminLogin>>>
    export type PostApiV1AuthAdminLoginMutationBody = AdminLoginRequest
    export type PostApiV1AuthAdminLoginMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Platform admin login
 */
export const usePostApiV1AuthAdminLogin = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthAdminLogin>>, TError,{data: AdminLoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthAdminLogin>>,
        TError,
        {data: AdminLoginRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthAdminLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get authenticated platform admin profile
 * @summary Get authenticated platform admin profile
 */
export const getApiV1AuthAdminMe = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AdminMeResponseEnvelope>(
      {url: `/api/v1/auth/admin/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1AuthAdminMeQueryKey = () => {
    return [
    `/api/v1/auth/admin/me`
    ] as const;
    }

    
export const getGetApiV1AuthAdminMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AuthAdminMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AuthAdminMe>>> = ({ signal }) => getApiV1AuthAdminMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AuthAdminMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AuthAdminMe>>>
export type GetApiV1AuthAdminMeQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1AuthAdminMe<TData = Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthAdminMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthAdminMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthAdminMe<TData = Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthAdminMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthAdminMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthAdminMe<TData = Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get authenticated platform admin profile
 */

export function useGetApiV1AuthAdminMe<TData = Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthAdminMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AuthAdminMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Platform admin token refresh; Rate-limited by IP
 * @summary Platform admin token refresh
 */
export const postApiV1AuthAdminRefresh = (
    refreshRequest: RefreshRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponseEnvelope>(
      {url: `/api/v1/auth/admin/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthAdminRefreshMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthAdminRefresh>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthAdminRefresh>>, TError,{data: RefreshRequest}, TContext> => {

const mutationKey = ['postApiV1AuthAdminRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthAdminRefresh>>, {data: RefreshRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthAdminRefresh(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthAdminRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthAdminRefresh>>>
    export type PostApiV1AuthAdminRefreshMutationBody = RefreshRequest
    export type PostApiV1AuthAdminRefreshMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Platform admin token refresh
 */
export const usePostApiV1AuthAdminRefresh = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthAdminRefresh>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthAdminRefresh>>,
        TError,
        {data: RefreshRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthAdminRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Rate-limited by IP; Tenant-scoped via X-Shop-ID header
 * @summary Rate-limited by IP
 */
export const postApiV1AuthCustomerLogin = (
    customerLoginRequest: CustomerLoginRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponseEnvelope>(
      {url: `/api/v1/auth/customer/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customerLoginRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthCustomerLoginMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthCustomerLogin>>, TError,{data: CustomerLoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthCustomerLogin>>, TError,{data: CustomerLoginRequest}, TContext> => {

const mutationKey = ['postApiV1AuthCustomerLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthCustomerLogin>>, {data: CustomerLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthCustomerLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthCustomerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthCustomerLogin>>>
    export type PostApiV1AuthCustomerLoginMutationBody = CustomerLoginRequest
    export type PostApiV1AuthCustomerLoginMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Rate-limited by IP
 */
export const usePostApiV1AuthCustomerLogin = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthCustomerLogin>>, TError,{data: CustomerLoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthCustomerLogin>>,
        TError,
        {data: CustomerLoginRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthCustomerLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get authenticated customer profile; Tenant-scoped
 * @summary Get authenticated customer profile
 */
export const getApiV1AuthCustomerMe = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CustomerMeResponseEnvelope>(
      {url: `/api/v1/auth/customer/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1AuthCustomerMeQueryKey = () => {
    return [
    `/api/v1/auth/customer/me`
    ] as const;
    }

    
export const getGetApiV1AuthCustomerMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AuthCustomerMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>> = ({ signal }) => getApiV1AuthCustomerMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AuthCustomerMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>>
export type GetApiV1AuthCustomerMeQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1AuthCustomerMe<TData = Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthCustomerMe<TData = Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthCustomerMe<TData = Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get authenticated customer profile
 */

export function useGetApiV1AuthCustomerMe<TData = Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthCustomerMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AuthCustomerMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update customer profile; Tenant-scoped
 * @summary Update customer profile
 */
export const patchApiV1AuthCustomerMe = (
    customerUpdateMeRequest?: CustomerUpdateMeRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<CustomerMeResponseEnvelope>(
      {url: `/api/v1/auth/customer/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: customerUpdateMeRequest
    },
      options);
    }
  


export const getPatchApiV1AuthCustomerMeMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthCustomerMe>>, TError,{data: CustomerUpdateMeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthCustomerMe>>, TError,{data: CustomerUpdateMeRequest}, TContext> => {

const mutationKey = ['patchApiV1AuthCustomerMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1AuthCustomerMe>>, {data: CustomerUpdateMeRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchApiV1AuthCustomerMe(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1AuthCustomerMeMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1AuthCustomerMe>>>
    export type PatchApiV1AuthCustomerMeMutationBody = CustomerUpdateMeRequest
    export type PatchApiV1AuthCustomerMeMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update customer profile
 */
export const usePatchApiV1AuthCustomerMe = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthCustomerMe>>, TError,{data: CustomerUpdateMeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1AuthCustomerMe>>,
        TError,
        {data: CustomerUpdateMeRequest},
        TContext
      > => {

      const mutationOptions = getPatchApiV1AuthCustomerMeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Change customer password; Tenant-scoped
 * @summary Change customer password
 */
export const patchApiV1AuthCustomerMePassword = (
    customerChangePasswordRequest: CustomerChangePasswordRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<MessageEnvelope>(
      {url: `/api/v1/auth/customer/me/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: customerChangePasswordRequest
    },
      options);
    }
  


export const getPatchApiV1AuthCustomerMePasswordMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthCustomerMePassword>>, TError,{data: CustomerChangePasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthCustomerMePassword>>, TError,{data: CustomerChangePasswordRequest}, TContext> => {

const mutationKey = ['patchApiV1AuthCustomerMePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1AuthCustomerMePassword>>, {data: CustomerChangePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchApiV1AuthCustomerMePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1AuthCustomerMePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1AuthCustomerMePassword>>>
    export type PatchApiV1AuthCustomerMePasswordMutationBody = CustomerChangePasswordRequest
    export type PatchApiV1AuthCustomerMePasswordMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Change customer password
 */
export const usePatchApiV1AuthCustomerMePassword = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthCustomerMePassword>>, TError,{data: CustomerChangePasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1AuthCustomerMePassword>>,
        TError,
        {data: CustomerChangePasswordRequest},
        TContext
      > => {

      const mutationOptions = getPatchApiV1AuthCustomerMePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Rate-limited by IP; Tenant-scoped via X-Shop-ID header
 * @summary Rate-limited by IP
 */
export const postApiV1AuthCustomerRefresh = (
    refreshRequest: RefreshRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponseEnvelope>(
      {url: `/api/v1/auth/customer/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthCustomerRefreshMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthCustomerRefresh>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthCustomerRefresh>>, TError,{data: RefreshRequest}, TContext> => {

const mutationKey = ['postApiV1AuthCustomerRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthCustomerRefresh>>, {data: RefreshRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthCustomerRefresh(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthCustomerRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthCustomerRefresh>>>
    export type PostApiV1AuthCustomerRefreshMutationBody = RefreshRequest
    export type PostApiV1AuthCustomerRefreshMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Rate-limited by IP
 */
export const usePostApiV1AuthCustomerRefresh = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthCustomerRefresh>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthCustomerRefresh>>,
        TError,
        {data: RefreshRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthCustomerRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Rate-limited by IP; Tenant-scoped via X-Shop-ID header
 * @summary Rate-limited by IP
 */
export const postApiV1AuthCustomerRegister = (
    customerRegisterRequest: CustomerRegisterRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponseEnvelope>(
      {url: `/api/v1/auth/customer/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customerRegisterRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthCustomerRegisterMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthCustomerRegister>>, TError,{data: CustomerRegisterRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthCustomerRegister>>, TError,{data: CustomerRegisterRequest}, TContext> => {

const mutationKey = ['postApiV1AuthCustomerRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthCustomerRegister>>, {data: CustomerRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthCustomerRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthCustomerRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthCustomerRegister>>>
    export type PostApiV1AuthCustomerRegisterMutationBody = CustomerRegisterRequest
    export type PostApiV1AuthCustomerRegisterMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Rate-limited by IP
 */
export const usePostApiV1AuthCustomerRegister = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthCustomerRegister>>, TError,{data: CustomerRegisterRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthCustomerRegister>>,
        TError,
        {data: CustomerRegisterRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthCustomerRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Exchange login_token for 2FA challenge response
 * @summary Exchange login_token for 2FA challenge response
 */
export const postApiV1AuthStaff2faChallenge = (
    challenge2FARequest: Challenge2FARequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponseEnvelope>(
      {url: `/api/v1/auth/staff/2fa/challenge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: challenge2FARequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthStaff2faChallengeMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faChallenge>>, TError,{data: Challenge2FARequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faChallenge>>, TError,{data: Challenge2FARequest}, TContext> => {

const mutationKey = ['postApiV1AuthStaff2faChallenge'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaff2faChallenge>>, {data: Challenge2FARequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthStaff2faChallenge(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaff2faChallengeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaff2faChallenge>>>
    export type PostApiV1AuthStaff2faChallengeMutationBody = Challenge2FARequest
    export type PostApiV1AuthStaff2faChallengeMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Exchange login_token for 2FA challenge response
 */
export const usePostApiV1AuthStaff2faChallenge = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faChallenge>>, TError,{data: Challenge2FARequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaff2faChallenge>>,
        TError,
        {data: Challenge2FARequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaff2faChallengeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Disable 2FA for authenticated staff
 * @summary Disable 2FA for authenticated staff
 */
export const postApiV1AuthStaff2faDisable = (
    verify2FARequest: Verify2FARequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MessageEnvelope>(
      {url: `/api/v1/auth/staff/2fa/disable`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verify2FARequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthStaff2faDisableMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faDisable>>, TError,{data: Verify2FARequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faDisable>>, TError,{data: Verify2FARequest}, TContext> => {

const mutationKey = ['postApiV1AuthStaff2faDisable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaff2faDisable>>, {data: Verify2FARequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthStaff2faDisable(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaff2faDisableMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaff2faDisable>>>
    export type PostApiV1AuthStaff2faDisableMutationBody = Verify2FARequest
    export type PostApiV1AuthStaff2faDisableMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Disable 2FA for authenticated staff
 */
export const usePostApiV1AuthStaff2faDisable = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faDisable>>, TError,{data: Verify2FARequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaff2faDisable>>,
        TError,
        {data: Verify2FARequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaff2faDisableMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Use recovery code for 2FA bypass (unauthenticated)
 * @summary Use recovery code for 2FA bypass (unauthenticated)
 */
export const postApiV1AuthStaff2faRecovery = (
    recoverAccountRequest: RecoverAccountRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponseEnvelope>(
      {url: `/api/v1/auth/staff/2fa/recovery`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: recoverAccountRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthStaff2faRecoveryMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faRecovery>>, TError,{data: RecoverAccountRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faRecovery>>, TError,{data: RecoverAccountRequest}, TContext> => {

const mutationKey = ['postApiV1AuthStaff2faRecovery'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaff2faRecovery>>, {data: RecoverAccountRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthStaff2faRecovery(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaff2faRecoveryMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaff2faRecovery>>>
    export type PostApiV1AuthStaff2faRecoveryMutationBody = RecoverAccountRequest
    export type PostApiV1AuthStaff2faRecoveryMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Use recovery code for 2FA bypass (unauthenticated)
 */
export const usePostApiV1AuthStaff2faRecovery = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faRecovery>>, TError,{data: RecoverAccountRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaff2faRecovery>>,
        TError,
        {data: RecoverAccountRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaff2faRecoveryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Initialize 2FA setup flow
 * @summary Initialize 2FA setup flow
 */
export const postApiV1AuthStaff2faSetup = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Setup2FAResponseEnvelope>(
      {url: `/api/v1/auth/staff/2fa/setup`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiV1AuthStaff2faSetupMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faSetup>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faSetup>>, TError,void, TContext> => {

const mutationKey = ['postApiV1AuthStaff2faSetup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaff2faSetup>>, void> = () => {
          

          return  postApiV1AuthStaff2faSetup(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaff2faSetupMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaff2faSetup>>>
    
    export type PostApiV1AuthStaff2faSetupMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Initialize 2FA setup flow
 */
export const usePostApiV1AuthStaff2faSetup = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faSetup>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaff2faSetup>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaff2faSetupMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Verify 2FA code during setup
 * @summary Verify 2FA code during setup
 */
export const postApiV1AuthStaff2faVerify = (
    verify2FARequest: Verify2FARequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MessageEnvelope>(
      {url: `/api/v1/auth/staff/2fa/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verify2FARequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthStaff2faVerifyMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faVerify>>, TError,{data: Verify2FARequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faVerify>>, TError,{data: Verify2FARequest}, TContext> => {

const mutationKey = ['postApiV1AuthStaff2faVerify'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaff2faVerify>>, {data: Verify2FARequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthStaff2faVerify(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaff2faVerifyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaff2faVerify>>>
    export type PostApiV1AuthStaff2faVerifyMutationBody = Verify2FARequest
    export type PostApiV1AuthStaff2faVerifyMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Verify 2FA code during setup
 */
export const usePostApiV1AuthStaff2faVerify = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaff2faVerify>>, TError,{data: Verify2FARequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaff2faVerify>>,
        TError,
        {data: Verify2FARequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaff2faVerifyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Rate-limited by IP
 * @summary Rate-limited by IP
 */
export const postApiV1AuthStaffForgotPassword = (
    forgotPasswordRequest: ForgotPasswordRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MessageEnvelope>(
      {url: `/api/v1/auth/staff/forgot-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthStaffForgotPasswordMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext> => {

const mutationKey = ['postApiV1AuthStaffForgotPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaffForgotPassword>>, {data: ForgotPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthStaffForgotPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaffForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaffForgotPassword>>>
    export type PostApiV1AuthStaffForgotPasswordMutationBody = ForgotPasswordRequest
    export type PostApiV1AuthStaffForgotPasswordMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Rate-limited by IP
 */
export const usePostApiV1AuthStaffForgotPassword = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaffForgotPassword>>,
        TError,
        {data: ForgotPasswordRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaffForgotPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Rate-limited by IP; Returns 200 with requires_2fa if 2FA enabled
 * @summary Rate-limited by IP
 */
export const postApiV1AuthStaffLogin = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostApiV1AuthStaffLogin200>(
      {url: `/api/v1/auth/staff/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthStaffLoginMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffLogin>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffLogin>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['postApiV1AuthStaffLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaffLogin>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthStaffLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaffLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaffLogin>>>
    export type PostApiV1AuthStaffLoginMutationBody = LoginRequest
    export type PostApiV1AuthStaffLoginMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Rate-limited by IP
 */
export const usePostApiV1AuthStaffLogin = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffLogin>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaffLogin>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaffLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get authenticated staff user profile
 * @summary Get authenticated staff user profile
 */
export const getApiV1AuthStaffMe = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MeResponseEnvelope>(
      {url: `/api/v1/auth/staff/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1AuthStaffMeQueryKey = () => {
    return [
    `/api/v1/auth/staff/me`
    ] as const;
    }

    
export const getGetApiV1AuthStaffMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AuthStaffMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AuthStaffMe>>> = ({ signal }) => getApiV1AuthStaffMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AuthStaffMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AuthStaffMe>>>
export type GetApiV1AuthStaffMeQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1AuthStaffMe<TData = Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthStaffMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthStaffMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthStaffMe<TData = Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthStaffMe>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthStaffMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthStaffMe<TData = Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get authenticated staff user profile
 */

export function useGetApiV1AuthStaffMe<TData = Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthStaffMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AuthStaffMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update authenticated staff user profile
 * @summary Update authenticated staff user profile
 */
export const patchApiV1AuthStaffMe = (
    staffUpdateProfileRequest?: StaffUpdateProfileRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UserResponseEnvelope>(
      {url: `/api/v1/auth/staff/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: staffUpdateProfileRequest
    },
      options);
    }
  


export const getPatchApiV1AuthStaffMeMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthStaffMe>>, TError,{data: StaffUpdateProfileRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthStaffMe>>, TError,{data: StaffUpdateProfileRequest}, TContext> => {

const mutationKey = ['patchApiV1AuthStaffMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1AuthStaffMe>>, {data: StaffUpdateProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchApiV1AuthStaffMe(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1AuthStaffMeMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1AuthStaffMe>>>
    export type PatchApiV1AuthStaffMeMutationBody = StaffUpdateProfileRequest
    export type PatchApiV1AuthStaffMeMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update authenticated staff user profile
 */
export const usePatchApiV1AuthStaffMe = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthStaffMe>>, TError,{data: StaffUpdateProfileRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1AuthStaffMe>>,
        TError,
        {data: StaffUpdateProfileRequest},
        TContext
      > => {

      const mutationOptions = getPatchApiV1AuthStaffMeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Change staff password
 * @summary Change staff password
 */
export const patchApiV1AuthStaffMePassword = (
    staffChangePasswordRequest: StaffChangePasswordRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<MessageEnvelope>(
      {url: `/api/v1/auth/staff/me/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: staffChangePasswordRequest
    },
      options);
    }
  


export const getPatchApiV1AuthStaffMePasswordMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthStaffMePassword>>, TError,{data: StaffChangePasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthStaffMePassword>>, TError,{data: StaffChangePasswordRequest}, TContext> => {

const mutationKey = ['patchApiV1AuthStaffMePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1AuthStaffMePassword>>, {data: StaffChangePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchApiV1AuthStaffMePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1AuthStaffMePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1AuthStaffMePassword>>>
    export type PatchApiV1AuthStaffMePasswordMutationBody = StaffChangePasswordRequest
    export type PatchApiV1AuthStaffMePasswordMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Change staff password
 */
export const usePatchApiV1AuthStaffMePassword = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AuthStaffMePassword>>, TError,{data: StaffChangePasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1AuthStaffMePassword>>,
        TError,
        {data: StaffChangePasswordRequest},
        TContext
      > => {

      const mutationOptions = getPatchApiV1AuthStaffMePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Rate-limited by IP
 * @summary Rate-limited by IP
 */
export const postApiV1AuthStaffRefresh = (
    refreshRequest: RefreshRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponseEnvelope>(
      {url: `/api/v1/auth/staff/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthStaffRefreshMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffRefresh>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffRefresh>>, TError,{data: RefreshRequest}, TContext> => {

const mutationKey = ['postApiV1AuthStaffRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaffRefresh>>, {data: RefreshRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthStaffRefresh(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaffRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaffRefresh>>>
    export type PostApiV1AuthStaffRefreshMutationBody = RefreshRequest
    export type PostApiV1AuthStaffRefreshMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Rate-limited by IP
 */
export const usePostApiV1AuthStaffRefresh = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffRefresh>>, TError,{data: RefreshRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaffRefresh>>,
        TError,
        {data: RefreshRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaffRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Rate-limited by IP
 * @summary Rate-limited by IP
 */
export const postApiV1AuthStaffRegister = (
    registerRequest: RegisterRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponseEnvelope>(
      {url: `/api/v1/auth/staff/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthStaffRegisterMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffRegister>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffRegister>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['postApiV1AuthStaffRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaffRegister>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthStaffRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaffRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaffRegister>>>
    export type PostApiV1AuthStaffRegisterMutationBody = RegisterRequest
    export type PostApiV1AuthStaffRegisterMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Rate-limited by IP
 */
export const usePostApiV1AuthStaffRegister = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffRegister>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaffRegister>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaffRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Rate-limited by IP
 * @summary Rate-limited by IP
 */
export const postApiV1AuthStaffResetPassword = (
    resetPasswordRequest: ResetPasswordRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MessageEnvelope>(
      {url: `/api/v1/auth/staff/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthStaffResetPasswordMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffResetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffResetPassword>>, TError,{data: ResetPasswordRequest}, TContext> => {

const mutationKey = ['postApiV1AuthStaffResetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaffResetPassword>>, {data: ResetPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthStaffResetPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaffResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaffResetPassword>>>
    export type PostApiV1AuthStaffResetPasswordMutationBody = ResetPasswordRequest
    export type PostApiV1AuthStaffResetPasswordMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Rate-limited by IP
 */
export const usePostApiV1AuthStaffResetPassword = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffResetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaffResetPassword>>,
        TError,
        {data: ResetPasswordRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaffResetPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Select current shop context for authenticated staff
 * @summary Select current shop context for authenticated staff
 */
export const postApiV1AuthStaffSelectShop = (
    selectShopRequest: SelectShopRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponseEnvelope>(
      {url: `/api/v1/auth/staff/select-shop`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: selectShopRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthStaffSelectShopMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffSelectShop>>, TError,{data: SelectShopRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffSelectShop>>, TError,{data: SelectShopRequest}, TContext> => {

const mutationKey = ['postApiV1AuthStaffSelectShop'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthStaffSelectShop>>, {data: SelectShopRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthStaffSelectShop(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthStaffSelectShopMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthStaffSelectShop>>>
    export type PostApiV1AuthStaffSelectShopMutationBody = SelectShopRequest
    export type PostApiV1AuthStaffSelectShopMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Select current shop context for authenticated staff
 */
export const usePostApiV1AuthStaffSelectShop = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthStaffSelectShop>>, TError,{data: SelectShopRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthStaffSelectShop>>,
        TError,
        {data: SelectShopRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthStaffSelectShopMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List roles; Tenant-scoped
 * @summary List roles
 */
export const getApiV1Roles = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/roles`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1RolesQueryKey = () => {
    return [
    `/api/v1/roles`
    ] as const;
    }

    
export const getGetApiV1RolesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Roles>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Roles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1RolesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Roles>>> = ({ signal }) => getApiV1Roles(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Roles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1RolesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Roles>>>
export type GetApiV1RolesQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1Roles<TData = Awaited<ReturnType<typeof getApiV1Roles>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Roles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Roles>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Roles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Roles<TData = Awaited<ReturnType<typeof getApiV1Roles>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Roles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Roles>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Roles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Roles<TData = Awaited<ReturnType<typeof getApiV1Roles>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Roles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List roles
 */

export function useGetApiV1Roles<TData = Awaited<ReturnType<typeof getApiV1Roles>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Roles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1RolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create custom role; Tenant-scoped
 * @summary Create custom role
 */
export const postApiV1Roles = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1RolesMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Roles>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Roles>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1Roles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Roles>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Roles(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1RolesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Roles>>>
    export type PostApiV1RolesMutationBody = GenericObject
    export type PostApiV1RolesMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Create custom role
 */
export const usePostApiV1Roles = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Roles>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Roles>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1RolesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete custom role; Tenant-scoped
 * @summary Delete custom role
 */
export const deleteApiV1RolesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/roles/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1RolesIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RolesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RolesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1RolesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1RolesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1RolesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1RolesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1RolesId>>>
    
    export type DeleteApiV1RolesIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Delete custom role
 */
export const useDeleteApiV1RolesId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RolesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1RolesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1RolesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Update role permissions; Tenant-scoped
 * @summary Update role permissions
 */
export const patchApiV1RolesId = (
    id: string,
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/roles/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1RolesIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1RolesId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1RolesId>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1RolesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1RolesId>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1RolesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1RolesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1RolesId>>>
    export type PatchApiV1RolesIdMutationBody = GenericObject
    export type PatchApiV1RolesIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update role permissions
 */
export const usePatchApiV1RolesId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1RolesId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1RolesId>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1RolesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get shop settings; Tenant-scoped
 * @summary Get shop settings
 */
export const getApiV1ShopsSettings = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ShopSettingsResponseEnvelope>(
      {url: `/api/v1/shops/settings`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1ShopsSettingsQueryKey = () => {
    return [
    `/api/v1/shops/settings`
    ] as const;
    }

    
export const getGetApiV1ShopsSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ShopsSettingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ShopsSettings>>> = ({ signal }) => getApiV1ShopsSettings(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ShopsSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ShopsSettings>>>
export type GetApiV1ShopsSettingsQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1ShopsSettings<TData = Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShopsSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShopsSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShopsSettings<TData = Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShopsSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShopsSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShopsSettings<TData = Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get shop settings
 */

export function useGetApiV1ShopsSettings<TData = Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ShopsSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update shop settings; Tenant-scoped
 * @summary Update shop settings
 */
export const patchApiV1ShopsSettings = (
    updateShopSettingsRequest?: UpdateShopSettingsRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ShopSettingsResponseEnvelope>(
      {url: `/api/v1/shops/settings`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateShopSettingsRequest
    },
      options);
    }
  


export const getPatchApiV1ShopsSettingsMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ShopsSettings>>, TError,{data: UpdateShopSettingsRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ShopsSettings>>, TError,{data: UpdateShopSettingsRequest}, TContext> => {

const mutationKey = ['patchApiV1ShopsSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1ShopsSettings>>, {data: UpdateShopSettingsRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchApiV1ShopsSettings(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1ShopsSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1ShopsSettings>>>
    export type PatchApiV1ShopsSettingsMutationBody = UpdateShopSettingsRequest
    export type PatchApiV1ShopsSettingsMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update shop settings
 */
export const usePatchApiV1ShopsSettings = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1ShopsSettings>>, TError,{data: UpdateShopSettingsRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1ShopsSettings>>,
        TError,
        {data: UpdateShopSettingsRequest},
        TContext
      > => {

      const mutationOptions = getPatchApiV1ShopsSettingsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List shop staff members; Tenant-scoped
 * @summary List shop staff members
 */
export const getApiV1ShopsStaff = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StaffMemberListEnvelope>(
      {url: `/api/v1/shops/staff`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1ShopsStaffQueryKey = () => {
    return [
    `/api/v1/shops/staff`
    ] as const;
    }

    
export const getGetApiV1ShopsStaffQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ShopsStaffQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ShopsStaff>>> = ({ signal }) => getApiV1ShopsStaff(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ShopsStaffQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ShopsStaff>>>
export type GetApiV1ShopsStaffQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1ShopsStaff<TData = Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShopsStaff>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShopsStaff>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShopsStaff<TData = Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ShopsStaff>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ShopsStaff>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ShopsStaff<TData = Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List shop staff members
 */

export function useGetApiV1ShopsStaff<TData = Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ShopsStaff>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ShopsStaffQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Add staff member to shop; Tenant-scoped
 * @summary Add staff member to shop
 */
export const postApiV1ShopsStaff = (
    addStaffRequest: AddStaffRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StaffMemberResponseEnvelope>(
      {url: `/api/v1/shops/staff`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addStaffRequest, signal
    },
      options);
    }
  


export const getPostApiV1ShopsStaffMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ShopsStaff>>, TError,{data: AddStaffRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ShopsStaff>>, TError,{data: AddStaffRequest}, TContext> => {

const mutationKey = ['postApiV1ShopsStaff'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ShopsStaff>>, {data: AddStaffRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1ShopsStaff(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ShopsStaffMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ShopsStaff>>>
    export type PostApiV1ShopsStaffMutationBody = AddStaffRequest
    export type PostApiV1ShopsStaffMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Add staff member to shop
 */
export const usePostApiV1ShopsStaff = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ShopsStaff>>, TError,{data: AddStaffRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ShopsStaff>>,
        TError,
        {data: AddStaffRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1ShopsStaffMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Remove staff member from shop; Tenant-scoped
 * @summary Remove staff member from shop
 */
export const deleteApiV1ShopsStaffId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<MessageEnvelope>(
      {url: `/api/v1/shops/staff/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1ShopsStaffIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ShopsStaffId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ShopsStaffId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1ShopsStaffId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1ShopsStaffId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1ShopsStaffId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1ShopsStaffIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1ShopsStaffId>>>
    
    export type DeleteApiV1ShopsStaffIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Remove staff member from shop
 */
export const useDeleteApiV1ShopsStaffId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ShopsStaffId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1ShopsStaffId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1ShopsStaffIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Assign role to staff member; Tenant-scoped
 * @summary Assign role to staff member
 */
export const patchApiV1StaffIdRole = (
    id: string,
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/staff/${id}/role`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1StaffIdRoleMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1StaffIdRole>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1StaffIdRole>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1StaffIdRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1StaffIdRole>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1StaffIdRole(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1StaffIdRoleMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1StaffIdRole>>>
    export type PatchApiV1StaffIdRoleMutationBody = GenericObject
    export type PatchApiV1StaffIdRoleMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Assign role to staff member
 */
export const usePatchApiV1StaffIdRole = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1StaffIdRole>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1StaffIdRole>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1StaffIdRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    