/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Envelope,
  ErrorResponse,
  GenericObject
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List customer addresses; Tenant-scoped
 * @summary List customer addresses
 */
export const getApiV1Addresses = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/addresses`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1AddressesQueryKey = () => {
    return [
    `/api/v1/addresses`
    ] as const;
    }

    
export const getGetApiV1AddressesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Addresses>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Addresses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AddressesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Addresses>>> = ({ signal }) => getApiV1Addresses(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Addresses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AddressesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Addresses>>>
export type GetApiV1AddressesQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1Addresses<TData = Awaited<ReturnType<typeof getApiV1Addresses>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Addresses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Addresses>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Addresses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Addresses<TData = Awaited<ReturnType<typeof getApiV1Addresses>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Addresses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Addresses>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Addresses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Addresses<TData = Awaited<ReturnType<typeof getApiV1Addresses>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Addresses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List customer addresses
 */

export function useGetApiV1Addresses<TData = Awaited<ReturnType<typeof getApiV1Addresses>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Addresses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AddressesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create address; Tenant-scoped
 * @summary Create address
 */
export const postApiV1Addresses = (
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/addresses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: genericObject, signal
    },
      options);
    }
  


export const getPostApiV1AddressesMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Addresses>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Addresses>>, TError,{data: GenericObject}, TContext> => {

const mutationKey = ['postApiV1Addresses'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Addresses>>, {data: GenericObject}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Addresses(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AddressesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Addresses>>>
    export type PostApiV1AddressesMutationBody = GenericObject
    export type PostApiV1AddressesMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Create address
 */
export const usePostApiV1Addresses = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Addresses>>, TError,{data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Addresses>>,
        TError,
        {data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPostApiV1AddressesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete address; Tenant-scoped
 * @summary Delete address
 */
export const deleteApiV1AddressesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/addresses/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1AddressesIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AddressesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AddressesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1AddressesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1AddressesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1AddressesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1AddressesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1AddressesId>>>
    
    export type DeleteApiV1AddressesIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Delete address
 */
export const useDeleteApiV1AddressesId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AddressesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1AddressesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1AddressesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Update address; Tenant-scoped
 * @summary Update address
 */
export const putApiV1AddressesId = (
    id: string,
    genericObject: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/addresses/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPutApiV1AddressesIdMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AddressesId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1AddressesId>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['putApiV1AddressesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1AddressesId>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1AddressesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1AddressesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1AddressesId>>>
    export type PutApiV1AddressesIdMutationBody = GenericObject
    export type PutApiV1AddressesIdMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Update address
 */
export const usePutApiV1AddressesId = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AddressesId>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1AddressesId>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPutApiV1AddressesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Set default address; Tenant-scoped
 * @summary Set default address
 */
export const patchApiV1AddressesIdDefault = (
    id: string,
    genericObject?: GenericObject,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Envelope>(
      {url: `/api/v1/addresses/${id}/default`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: genericObject
    },
      options);
    }
  


export const getPatchApiV1AddressesIdDefaultMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AddressesIdDefault>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AddressesIdDefault>>, TError,{id: string;data: GenericObject}, TContext> => {

const mutationKey = ['patchApiV1AddressesIdDefault'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1AddressesIdDefault>>, {id: string;data: GenericObject}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiV1AddressesIdDefault(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1AddressesIdDefaultMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1AddressesIdDefault>>>
    export type PatchApiV1AddressesIdDefaultMutationBody = GenericObject
    export type PatchApiV1AddressesIdDefaultMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Set default address
 */
export const usePatchApiV1AddressesIdDefault = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AddressesIdDefault>>, TError,{id: string;data: GenericObject}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1AddressesIdDefault>>,
        TError,
        {id: string;data: GenericObject},
        TContext
      > => {

      const mutationOptions = getPatchApiV1AddressesIdDefaultMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    