-- migrations/000033_seed_feature_flags.up.sql
-- Re-seed plan feature flags with the complete feature set accumulated across
-- Phases 13–33. Uses ON CONFLICT so re-running is safe and idempotent.

UPDATE plans SET features = '{
  "custom_domain":           false,
  "coupons":                 true,
  "shipping_zones":          true,
  "core_analytics":          true,
  "wishlists":               true,
  "product_reviews":         true,
  "social_proof":            false,
  "abandoned_cart_recovery": false,
  "notifications_in_app":    true,
  "notifications_push":      false,
  "notifications_sse":       false,
  "multi_currency":          false,
  "localization":            true,
  "multi_warehouse":         false,
  "inventory_bundles":       false,
  "pre_orders":              false,
  "reorder_automation":      false,
  "flash_sales":             false,
  "tiered_discounts":        false,
  "loyalty_program":         false,
  "referral_program":        false,
  "pwa":                     true,
  "seo_basic":               true,
  "seo_scoring":             false,
  "seo_redirects":           false,
  "seo_advanced":            false,
  "webhooks":                false,
  "advanced_analytics":      false,
  "analytics_export":        false,
  "realtime_analytics":      false,
  "support_automation":      false,
  "priority_support":        false,
  "ai_text":                 false,
  "ai_seo":                  false,
  "ai_translate":            false,
  "ai_email":                false,
  "ai_reports":              false,
  "ai_engine":               false,
  "ai_vision":               false
}'::jsonb
WHERE name = 'basic';

UPDATE plans SET features = '{
  "custom_domain":           true,
  "coupons":                 true,
  "shipping_zones":          true,
  "core_analytics":          true,
  "realtime_analytics":      true,
  "standard_analytics":      true,
  "analytics_export":        true,
  "wishlists":               true,
  "product_reviews":         true,
  "review_moderation":       true,
  "social_proof":            true,
  "abandoned_cart_recovery": true,
  "notifications_in_app":    true,
  "notifications_push":      true,
  "notifications_sse":       true,
  "multi_currency":          true,
  "localization":            true,
  "multi_warehouse":         false,
  "inventory_bundles":       true,
  "pre_orders":              true,
  "reorder_automation":      false,
  "flash_sales":             true,
  "tiered_discounts":        true,
  "loyalty_program":         false,
  "referral_program":        false,
  "pwa":                     true,
  "seo_basic":               true,
  "seo_scoring":             true,
  "seo_redirects":           true,
  "seo_advanced":            false,
  "webhooks":                true,
  "advanced_analytics":      false,
  "support_automation":      false,
  "priority_support":        false,
  "ai_text":                 true,
  "ai_seo":                  true,
  "ai_translate":            true,
  "ai_email":                true,
  "ai_reports":              false,
  "ai_engine":               true,
  "ai_vision":               false
}'::jsonb
WHERE name = 'professional';

UPDATE plans SET features = '{
  "custom_domain":           true,
  "coupons":                 true,
  "shipping_zones":          true,
  "core_analytics":          true,
  "realtime_analytics":      true,
  "standard_analytics":      true,
  "analytics_export":        true,
  "advanced_analytics":      true,
  "analytics_alerts":        true,
  "analytics_api_access":    true,
  "wishlists":               true,
  "product_reviews":         true,
  "review_moderation":       true,
  "social_proof":            true,
  "abandoned_cart_recovery": true,
  "notifications_in_app":    true,
  "notifications_push":      true,
  "notifications_sse":       true,
  "multi_currency":          true,
  "localization":            true,
  "multi_warehouse":         true,
  "inventory_bundles":       true,
  "pre_orders":              true,
  "reorder_automation":      true,
  "flash_sales":             true,
  "tiered_discounts":        true,
  "loyalty_program":         true,
  "referral_program":        true,
  "pwa":                     true,
  "seo_basic":               true,
  "seo_scoring":             true,
  "seo_redirects":           true,
  "seo_advanced":            true,
  "seo_search_console":      true,
  "webhooks":                true,
  "support_automation":      true,
  "priority_support":        true,
  "ai_text":                 true,
  "ai_seo":                  true,
  "ai_translate":            true,
  "ai_email":                true,
  "ai_reports":              true,
  "ai_engine":               true,
  "ai_vision":               true,
  "ai_forecasting":          true,
  "ai_churn_scoring":        true
}'::jsonb
WHERE name = 'premium';
