/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */

export type GetApiV1PlatformAdminShopsOrder = typeof GetApiV1PlatformAdminShopsOrder[keyof typeof GetApiV1PlatformAdminShopsOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1PlatformAdminShopsOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
