/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import type { OrderItemResponse } from './orderItemResponse';
import type { OrderResponseShippingAddress } from './orderResponseShippingAddress';

export interface OrderResponse {
  coupon_id?: string;
  created_at?: string;
  customer_id?: string;
  discount_amount?: string;
  id?: string;
  items?: OrderItemResponse[];
  order_number?: number;
  shipping_address?: OrderResponseShippingAddress;
  shipping_fee?: string;
  shop_id?: string;
  status?: string;
  total_price?: string;
}
