/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import type { PlanResponseFeatures } from './planResponseFeatures';

export interface PlanResponse {
  created_at?: string;
  features?: PlanResponseFeatures;
  id?: string;
  max_products?: number;
  max_staff_accounts?: number;
  max_storage_mb?: number;
  monthly_price?: string;
  name?: string;
  transaction_fee_percent?: string;
}
