/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import type { ImageResponse } from './imageResponse';
import type { VariantResponse } from './variantResponse';

export interface ProductResponse {
  category_id?: string;
  compare_at_price?: string;
  created_at?: string;
  description?: string;
  id?: string;
  images?: ImageResponse[];
  low_stock?: boolean;
  low_stock_threshold?: number;
  price?: string;
  seo_description?: string;
  seo_title?: string;
  shop_id?: string;
  sku?: string;
  slug?: string;
  status?: string;
  stock_quantity?: number;
  title?: string;
  track_inventory?: boolean;
  variants?: VariantResponse[];
}
