-- ==================== Products ====================

-- name: CreateProduct :one
INSERT INTO products (
    shop_id, category_id, title, slug, description, price,
    compare_at_price, track_inventory, stock_quantity, low_stock_threshold, sku, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING *;

-- name: GetProduct :one
SELECT * FROM products
WHERE id = $1 AND shop_id = $2 AND deleted_at IS NULL;

-- name: GetProductBySlug :one
SELECT * FROM products
WHERE slug = $1 AND shop_id = $2 AND deleted_at IS NULL;

-- name: GetProductBySKU :one
SELECT * FROM products
WHERE sku = $1 AND shop_id = $2 AND deleted_at IS NULL;

-- name: ListProducts :many
SELECT * FROM products
WHERE shop_id = $1
    AND deleted_at IS NULL
    AND (sqlc.narg('status')::varchar IS NULL OR status = sqlc.narg('status'))
    AND (sqlc.narg('category_id')::uuid IS NULL OR category_id = sqlc.narg('category_id'))
ORDER BY title ASC
LIMIT $2 OFFSET $3;

-- name: ListProductsCursor :many
-- Keyset pagination ordered by (created_at DESC, id DESC).
-- Pass cursor_created_at + cursor_id from the last row to get the next page.
-- Leave them NULL to get the first page.
SELECT * FROM products
WHERE shop_id = $1
    AND deleted_at IS NULL
    AND (sqlc.narg('status')::varchar IS NULL OR status = sqlc.narg('status'))
    AND (sqlc.narg('category_id')::uuid IS NULL OR category_id = sqlc.narg('category_id'))
    AND (sqlc.narg('cursor_created_at')::timestamptz IS NULL
         OR (created_at, id) < (sqlc.narg('cursor_created_at')::timestamptz, sqlc.narg('cursor_id')::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $2;

-- name: CountProducts :one
SELECT COUNT(*) FROM products
WHERE shop_id = $1
    AND deleted_at IS NULL
    AND (sqlc.narg('status')::varchar IS NULL OR status = sqlc.narg('status'))
    AND (sqlc.narg('category_id')::uuid IS NULL OR category_id = sqlc.narg('category_id'));

-- name: UpdateProduct :one
UPDATE products SET
    title = COALESCE(sqlc.narg('title'), title),
    slug = COALESCE(sqlc.narg('slug'), slug),
    description = COALESCE(sqlc.narg('description'), description),
    price = COALESCE(sqlc.narg('price'), price),
    compare_at_price = COALESCE(sqlc.narg('compare_at_price'), compare_at_price),
    track_inventory = COALESCE(sqlc.narg('track_inventory'), track_inventory),
    stock_quantity = COALESCE(sqlc.narg('stock_quantity'), stock_quantity),
    low_stock_threshold = COALESCE(sqlc.narg('low_stock_threshold'), low_stock_threshold),
    sku = COALESCE(sqlc.narg('sku'), sku),
    status = COALESCE(sqlc.narg('status'), status),
    category_id = COALESCE(sqlc.narg('category_id'), category_id)
WHERE id = @id AND shop_id = @shop_id
RETURNING *;

-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1 AND shop_id = $2;

-- name: DecrementProductStock :one
-- Atomically decrements stock only when sufficient units are available.
-- Returns the updated row; returns no rows when stock is insufficient.
UPDATE products
SET stock_quantity = stock_quantity - $3
WHERE id = $1
  AND shop_id = $2
  AND track_inventory = TRUE
  AND stock_quantity >= $3
RETURNING id, stock_quantity, low_stock_threshold;

-- name: SetProductStock :one
UPDATE products
SET stock_quantity = $3
WHERE id = $1 AND shop_id = $2
RETURNING *;

-- name: SetProductLowStockThreshold :one
UPDATE products
SET low_stock_threshold = $3
WHERE id = $1 AND shop_id = $2
RETURNING *;

-- name: UpdateProductSEO :exec
UPDATE products
SET seo_title = $3, seo_description = $4
WHERE id = $1 AND shop_id = $2;

-- name: SearchProducts :many
-- Full-text trigram search. Results ordered by similarity descending.
-- AI seam: this query will be replaced by a pgvector cosine similarity search
--          once product embeddings are generated by the AI Engine.
SELECT id, shop_id, category_id, title, slug, description, price,
       compare_at_price, track_inventory, stock_quantity, low_stock_threshold,
       sku, status, seo_title, seo_description, created_at, deleted_at,
       similarity(title, @query::text) AS title_sim
FROM products
WHERE shop_id = @shop_id
  AND deleted_at IS NULL
  AND (title % @query::text OR description % @query::text)
ORDER BY title_sim DESC
LIMIT @max_results::int;

-- name: GetCopurchasedProducts :many
SELECT oi2.product_id, COUNT(*) AS co_count
FROM order_items oi1
JOIN order_items oi2 ON oi1.order_id = oi2.order_id
JOIN orders o ON o.id = oi1.order_id
WHERE o.shop_id = @shop_id
  AND oi1.product_id = @product_id
  AND oi2.product_id != @product_id
  AND o.status = 'completed'
GROUP BY oi2.product_id
ORDER BY co_count DESC
LIMIT @max_results::int;

-- name: ListProductsByCategory :many
SELECT * FROM products
WHERE shop_id = $1 AND category_id = $2 AND deleted_at IS NULL
ORDER BY title ASC;

-- name: SoftDeleteProduct :exec
UPDATE products SET deleted_at = NOW()
WHERE id = $1 AND shop_id = $2 AND deleted_at IS NULL;

-- name: RestoreProduct :one
UPDATE products SET deleted_at = NULL
WHERE id = $1 AND shop_id = $2 AND deleted_at IS NOT NULL
RETURNING *;

-- name: ListDeletedProducts :many
SELECT * FROM products
WHERE shop_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC;

-- name: SearchProductsFTS :many
SELECT
    p.id, p.shop_id, p.category_id, p.title, p.slug, p.description, p.price,
    p.compare_at_price, p.track_inventory, p.stock_quantity, p.low_stock_threshold,
    p.sku, p.status, p.seo_title, p.seo_description, p.created_at, p.deleted_at,
    ts_rank(p.search_vector, plainto_tsquery('english', @query::text)) AS rank
FROM products p
WHERE p.shop_id = @shop_id
  AND p.deleted_at IS NULL
  AND (
      p.search_vector @@ plainto_tsquery('english', @query::text)
      OR similarity(p.title, @query::text) > 0.2
  )
  AND (@min_price::numeric IS NULL OR p.price >= @min_price)
  AND (@max_price::numeric IS NULL OR p.price <= @max_price)
  AND (@category_id = '00000000-0000-0000-0000-000000000000'::uuid OR p.category_id = @category_id)
ORDER BY rank DESC, p.title
LIMIT @lim OFFSET @off;

-- name: GetSearchFacets :many
SELECT key, value, COUNT(*)::int AS count
FROM product_attributes
WHERE shop_id = @shop_id
GROUP BY key, value
ORDER BY key, count DESC;

-- name: GetPopularFilters :many
SELECT key, COUNT(DISTINCT value)::int AS distinct_values
FROM product_attributes
WHERE shop_id = @shop_id
GROUP BY key
ORDER BY distinct_values DESC
LIMIT 20;
