/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Nexus Commerce API
 * Portfolio-ready internal OpenAPI specification for Nexus Commerce.

This contract documents the complete backend route surface across commerce, operations, and platform modules.

Highlights:
- Multi-tenant architecture using X-Shop-ID scoping
- JWT-based role-aware access (staff, customer, platform admin)
- End-to-end commerce modules (catalog, cart, checkout, orders, returns)
- Platform services (billing, subscriptions, analytics, AI, SEO, notifications)

This spec is intended for internal engineering and portfolio demonstration.
 * OpenAPI spec version: 2026.03
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BillingStatusResponseEnvelope,
  ChangePlanRequest,
  ErrorResponse,
  InvoiceListEnvelope,
  OnboardingChecklistEnvelope,
  PlanListEnvelope,
  PlanResponseEnvelope
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List invoices; Tenant-scoped
 * @summary List invoices
 */
export const getApiV1BillingInvoices = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InvoiceListEnvelope>(
      {url: `/api/v1/billing/invoices`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1BillingInvoicesQueryKey = () => {
    return [
    `/api/v1/billing/invoices`
    ] as const;
    }

    
export const getGetApiV1BillingInvoicesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BillingInvoicesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BillingInvoices>>> = ({ signal }) => getApiV1BillingInvoices(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BillingInvoicesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BillingInvoices>>>
export type GetApiV1BillingInvoicesQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1BillingInvoices<TData = Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BillingInvoices>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BillingInvoices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BillingInvoices<TData = Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BillingInvoices>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BillingInvoices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BillingInvoices<TData = Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List invoices
 */

export function useGetApiV1BillingInvoices<TData = Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingInvoices>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BillingInvoicesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get onboarding checklist; Tenant-scoped
 * @summary Get onboarding checklist
 */
export const getApiV1BillingOnboarding = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OnboardingChecklistEnvelope>(
      {url: `/api/v1/billing/onboarding`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1BillingOnboardingQueryKey = () => {
    return [
    `/api/v1/billing/onboarding`
    ] as const;
    }

    
export const getGetApiV1BillingOnboardingQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BillingOnboardingQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BillingOnboarding>>> = ({ signal }) => getApiV1BillingOnboarding(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BillingOnboardingQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BillingOnboarding>>>
export type GetApiV1BillingOnboardingQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1BillingOnboarding<TData = Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BillingOnboarding>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BillingOnboarding>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BillingOnboarding<TData = Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BillingOnboarding>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BillingOnboarding>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BillingOnboarding<TData = Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get onboarding checklist
 */

export function useGetApiV1BillingOnboarding<TData = Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingOnboarding>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BillingOnboardingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Change subscription plan; Tenant-scoped
 * @summary Change subscription plan
 */
export const patchApiV1BillingPlan = (
    changePlanRequest: ChangePlanRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<BillingStatusResponseEnvelope>(
      {url: `/api/v1/billing/plan`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: changePlanRequest
    },
      options);
    }
  


export const getPatchApiV1BillingPlanMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1BillingPlan>>, TError,{data: ChangePlanRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1BillingPlan>>, TError,{data: ChangePlanRequest}, TContext> => {

const mutationKey = ['patchApiV1BillingPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1BillingPlan>>, {data: ChangePlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchApiV1BillingPlan(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1BillingPlanMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1BillingPlan>>>
    export type PatchApiV1BillingPlanMutationBody = ChangePlanRequest
    export type PatchApiV1BillingPlanMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Change subscription plan
 */
export const usePatchApiV1BillingPlan = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1BillingPlan>>, TError,{data: ChangePlanRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1BillingPlan>>,
        TError,
        {data: ChangePlanRequest},
        TContext
      > => {

      const mutationOptions = getPatchApiV1BillingPlanMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get billing status for shop; Tenant-scoped
 * @summary Get billing status for shop
 */
export const getApiV1BillingStatus = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BillingStatusResponseEnvelope>(
      {url: `/api/v1/billing/status`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1BillingStatusQueryKey = () => {
    return [
    `/api/v1/billing/status`
    ] as const;
    }

    
export const getGetApiV1BillingStatusQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BillingStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BillingStatus>>> = ({ signal }) => getApiV1BillingStatus(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BillingStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BillingStatus>>>
export type GetApiV1BillingStatusQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1BillingStatus<TData = Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BillingStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BillingStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BillingStatus<TData = Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BillingStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BillingStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BillingStatus<TData = Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get billing status for shop
 */

export function useGetApiV1BillingStatus<TData = Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BillingStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BillingStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * List subscription plans; Public
 * @summary List subscription plans
 */
export const getApiV1Plans = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PlanListEnvelope>(
      {url: `/api/v1/plans`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1PlansQueryKey = () => {
    return [
    `/api/v1/plans`
    ] as const;
    }

    
export const getGetApiV1PlansQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Plans>>, TError = ErrorResponse | ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plans>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PlansQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Plans>>> = ({ signal }) => getApiV1Plans(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plans>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PlansQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Plans>>>
export type GetApiV1PlansQueryError = ErrorResponse | ErrorResponse


export function useGetApiV1Plans<TData = Awaited<ReturnType<typeof getApiV1Plans>>, TError = ErrorResponse | ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plans>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Plans>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Plans>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Plans<TData = Awaited<ReturnType<typeof getApiV1Plans>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plans>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Plans>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Plans>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Plans<TData = Awaited<ReturnType<typeof getApiV1Plans>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plans>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List subscription plans
 */

export function useGetApiV1Plans<TData = Awaited<ReturnType<typeof getApiV1Plans>>, TError = ErrorResponse | ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Plans>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PlansQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get plan by ID; Public
 * @summary Get plan by ID
 */
export const getApiV1PlansId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PlanResponseEnvelope>(
      {url: `/api/v1/plans/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1PlansIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/plans/${id}`
    ] as const;
    }

    
export const getGetApiV1PlansIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PlansId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlansId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PlansIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PlansId>>> = ({ signal }) => getApiV1PlansId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlansId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PlansIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PlansId>>>
export type GetApiV1PlansIdQueryError = ErrorResponse | ErrorResponse | ErrorResponse


export function useGetApiV1PlansId<TData = Awaited<ReturnType<typeof getApiV1PlansId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlansId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PlansId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PlansId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PlansId<TData = Awaited<ReturnType<typeof getApiV1PlansId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlansId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PlansId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PlansId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PlansId<TData = Awaited<ReturnType<typeof getApiV1PlansId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlansId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get plan by ID
 */

export function useGetApiV1PlansId<TData = Awaited<ReturnType<typeof getApiV1PlansId>>, TError = ErrorResponse | ErrorResponse | ErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlansId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PlansIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



